//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YJC.Toolkit.Razor.Dynamic {
    using System;
    using System.Text;
    using System.Collections.Generic;
    using System.Linq;
    using System.IO;
    using YJC.Toolkit.Razor;
    using YJC.Toolkit.Web;
    
    
    public class dcinternalfilemituhzwdsmanagewebxmlrazorcxcsdocumentlistcshtml : YJC.Toolkit.Razor.NormalListTemplate {
        
#line hidden
        
        public dcinternalfilemituhzwdsmanagewebxmlrazorcxcsdocumentlistcshtml() {
        }
        
        public override void Execute() {
        }
    }
}
