//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YJC.Toolkit.Razor.Dynamic {
    using System;
    using System.Text;
    using System.Collections.Generic;
    using System.Linq;
    using System.IO;
    using YJC.Toolkit.Razor;
    using YJC.Toolkit.Web;
    using System.Data;
    using YJC.Toolkit.Sys;
    
    
    public class dcinternalfilemituhzwdsmanagewebxmlrazorcxcsdocumentdetailcshtml : YJC.Toolkit.Razor.ToolkitTemplate {
        
#line hidden
        
        public dcinternalfilemituhzwdsmanagewebxmlrazorcxcsdocumentdetailcshtml() {
        }
        
        public override void Execute() {
  
    DataSet dataSet = (DataSet)Model;
    DataRow row = dataSet.GetRow("CS_DOCUMENT");
    string title = row.GetString("Title");
    DataTable attachTable = dataSet.Tables["CS_DOC_ATTACHMENT"];
    string context = string.Empty;
    if (!string.IsNullOrEmpty(row.GetString("SourceId")))
    {
        context = "Tools";
    }

WriteLiteral("\r\n<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    <title>");

      Write(title);

WriteLiteral("</title>\r\n    <meta");

WriteLiteral(" http-equiv=\"X-UA-Compatible\"");

WriteLiteral(" content=\"IE=edge\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" http-equiv=\"Content-Type\"");

WriteLiteral(" content=\"text/html; charset=utf-8\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable" +
"=0;\"");

WriteLiteral(" />\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteAttribute("href", Tuple.Create(" href=\"", 812), Tuple.Create("\"", 885)
, Tuple.Create(Tuple.Create("", 819), Tuple.Create<System.Object, System.Int32>("toolkitjs/v5/bootstrap/css/bootstrap.min.css".AppVirutalPath()
, 819), false)
);

WriteLiteral(" />\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteAttribute("href", Tuple.Create(" href=\"", 933), Tuple.Create("\"", 986)
, Tuple.Create(Tuple.Create("", 940), Tuple.Create<System.Object, System.Int32>("usercss/document.css?v=2".AppVirutalPath()
, 940), false)
);

WriteLiteral(" />\r\n</head>\r\n<body");

WriteLiteral(" data-webPath=\"");

               Write(HtmlUtil.AppVirtualPath);

WriteLiteral("\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(" name=\"_top\"");

WriteLiteral(" id=\"_top\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" id=\"metaData\"");

WriteLiteral(" class=\"Hide\"");

WriteLiteral(" data-toolbar=\"true\"");

WriteLiteral(" data-option=\"true\"");

WriteLiteral(" data-title=\"");

                                                                                      Write(StringUtil.EscapeHtmlAttribute(title));

WriteLiteral("\"");

WriteLiteral(" data-desc=\"");

                                                                                                                                         Write(StringUtil.EscapeHtmlAttribute(row.GetString("PrevContent")));

WriteLiteral("\"");

WriteLiteral(" data-link=\"");

                                                                                                                                                                                                                    Write("~/doc.vp?" + row.GetString("DocId"));

WriteLiteral("\"");

WriteLiteral(" data-img=\"~/pic/sys/shui.jpg\"");

WriteLiteral("></div>\r\n");

        
         if (!string.IsNullOrEmpty(row.GetString("OrginOrg")))
        {

WriteLiteral("            <h1>");

           Write(row.GetString("OrginOrg"));

WriteLiteral("<br />");

                                           Write(title);

WriteLiteral("</h1>\r\n");

        }
        else
        {

WriteLiteral("            <h1>");

           Write(title);

WriteLiteral("</h1>\r\n");

        }

WriteLiteral("        </h1>\r\n");

        
         if (!string.IsNullOrEmpty(row.GetString("Number")))
        {

WriteLiteral("            <p");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">");

                              Write(row.GetString("Number"));

WriteLiteral("</p>\r\n");

        }

WriteLiteral("        <div>\r\n");

WriteLiteral("            ");

       Write(row.GetString("Content"));

WriteLiteral("\r\n        </div>\r\n");

        
         if (attachTable != null && attachTable.Rows.Count > 0)
        {

WriteLiteral("            <ul");

WriteLiteral(" class=\"list-group\"");

WriteLiteral(">\r\n");

                
                 foreach (DataRow attachRow in attachTable.Rows)
                {

WriteLiteral("                    <li");

WriteLiteral(" class=\"list-group-item\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" target=\"_blank\"");

WriteAttribute("href", Tuple.Create(" href=\"", 2131), Tuple.Create("\"", 2215)
, Tuple.Create(Tuple.Create("", 2138), Tuple.Create<System.Object, System.Int32>(HtmlUtil.GetDownloadUrl(attachRow.GetString("FileId"), true, false, context)
, 2138), false)
);

WriteLiteral(">");

                                                                                                                           Write(attachRow.GetString("FileName"));

WriteLiteral("</a>\r\n                    </li>\r\n");

                }

WriteLiteral("            </ul>\r\n");

        }

WriteLiteral("        <div");

WriteLiteral(" class=\"text-right mt10 mb10 f16\"");

WriteLiteral(">\r\n            <a");

WriteLiteral(" href=\"#_top\"");

WriteLiteral(">返回顶部</a>\r\n        </div>\r\n    </div>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 2479), Tuple.Create("\"", 2543)
, Tuple.Create(Tuple.Create("", 2485), Tuple.Create<System.Object, System.Int32>("toolkitjs/v5/lib/jquery-1.7.2.min.js".AppVirutalPath()
, 2485), false)
);

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 2590), Tuple.Create("\"", 2660)
, Tuple.Create(Tuple.Create("", 2596), Tuple.Create<System.Object, System.Int32>("toolkitjs/v5/bootstrap/js/bootstrap.min.js".AppVirutalPath()
, 2596), false)
);

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 2707), Tuple.Create("\"", 2766)
, Tuple.Create(Tuple.Create("", 2713), Tuple.Create<System.Object, System.Int32>("toolkitjs/v5/toolkit/toolkit.js".AppVirutalPath()
, 2713), false)
);

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 2813), Tuple.Create("\"", 2883)
, Tuple.Create(Tuple.Create("", 2819), Tuple.Create<System.Object, System.Int32>("toolkitjs/v5/toolkit/coreT/toolkit.page.js".AppVirutalPath()
, 2819), false)
);

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 2930), Tuple.Create("\"", 3006)
, Tuple.Create(Tuple.Create("", 2936), Tuple.Create<System.Object, System.Int32>("toolkitjs/v5/toolkit/coreT/toolkit.weixin.js?v=4".AppVirutalPath()
, 2936), false)
);

WriteLiteral("></script>\r\n</body>\r\n</html>\r\n");

        }
    }
}
