//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YJC.Toolkit.Razor.Dynamic {
    using System;
    using System.Text;
    using System.Collections.Generic;
    using System.Linq;
    using System.IO;
    using YJC.Toolkit.Razor;
    using YJC.Toolkit.Web;
    using System.Data;
    using YJC.Toolkit.Sys;
    
    
    public class dcinternalfilemituhzwdsmanagewebxmlrazorcxcscatelogfieldcshtml : YJC.Toolkit.Razor.BootcssListTemplate {
        
#line hidden
        
        public dcinternalfilemituhzwdsmanagewebxmlrazorcxcscatelogfieldcshtml() {
        }
        
        public override void Execute() {
   
    DataRow row = (DataRow)(Model.Row);
    string sourceId = row.GetString("SourceId");

WriteLiteral("\r\n<td>");

Write(row.GetString("Catelog_Name"));

WriteLiteral("\r\n");

    
     if (!string.IsNullOrEmpty(sourceId))
    {

WriteLiteral("        <img");

WriteAttribute("src", Tuple.Create(" src=\"", 317), Tuple.Create("\"", 361)
, Tuple.Create(Tuple.Create("", 323), Tuple.Create<System.Object, System.Int32>("pic/sys/copy.jpg".AppVirutalPath()
, 323), false)
);

WriteLiteral(" style=\"width:16px;margin-left:1px\"");

WriteLiteral(" />\r\n");

    }

WriteLiteral("</td>\r\n\r\n");

        }
    }
}
