//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConvertToJson {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DataString {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataString() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConvertToJson.DataString", typeof(DataString).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///    &quot;errcode&quot;: 0,
        ///    &quot;errmsg&quot;: &quot;success&quot;, 
        ///    &quot;template_id&quot;: 123456
        ///} 的本地化字符串。
        /// </summary>
        internal static string AddTemplateResponse {
            get {
                return ResourceManager.GetString("AddTemplateResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///	&quot;errcode&quot;: 0,
        ///	&quot;errmsg&quot;: &quot;success&quot;,
        ///	&quot;groups_detail&quot;: [
        ///		{
        ///		  &quot;group_id&quot;: 200077549,
        ///		  &quot;group_name&quot;: &quot;最新上架&quot;
        ///		},
        ///		{
        ///		  &quot;group_id&quot;: 200079772,
        ///		  &quot;group_name&quot;: &quot;全球热卖&quot;
        ///		}
        ///	]
        ///} 的本地化字符串。
        /// </summary>
        internal static string AllGroupResponse {
            get {
                return ResourceManager.GetString("AllGroupResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///  &quot;errcode&quot;: 0,
        ///  &quot;errmsg&quot;: &quot;success&quot;,
        ///  &quot;properties&quot;: [
        ///    {
        ///      &quot;id&quot;: &quot;1075741879&quot;,
        ///      &quot;name&quot;: &quot;品牌&quot;,
        ///      &quot;property_value&quot;: [
        ///        {
        ///          &quot;id&quot;: &quot;200050867&quot;,
        ///          &quot;name&quot;: &quot;VIC&amp;#38&quot;
        ///        },
        ///        {
        ///          &quot;id&quot;: &quot;200050868&quot;,
        ///          &quot;name&quot;: &quot;Kate&amp;#38&quot;
        ///        },
        ///        {
        ///          &quot;id&quot;: &quot;200050971&quot;,
        ///          &quot;name&quot;: &quot;M&amp;#38&quot;
        ///        },
        ///        {
        ///          &quot;id&quot;: &quot;200050972&quot;,
        ///          &quot;name&quot;: &quot;Black&amp;#38&quot;
        ///        }
        ///      ]
        ///    } 
        ///  ]
        ///} 的本地化字符串。
        /// </summary>
        internal static string AllPropertyResponse {
            get {
                return ResourceManager.GetString("AllPropertyResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///  &quot;errcode&quot;: 0,
        ///  &quot;errmsg&quot;: &quot;success&quot;,
        ///  &quot;sku_table&quot;: [
        ///    {
        ///      &quot;id&quot;: &quot;1075741873&quot;,
        ///      &quot;name&quot;: &quot;颜色&quot;,
        ///      &quot;value_list&quot;: [
        ///        {
        ///          &quot;id&quot;: &quot;1079742375&quot;,
        ///          &quot;name&quot;: &quot;撞色&quot;
        ///        },
        ///        {
        ///          &quot;id&quot;: &quot;1079742376&quot;,
        ///          &quot;name&quot;: &quot;桔色&quot;
        ///        }
        ///      ]
        ///    }
        ///  ]
        ///} 的本地化字符串。
        /// </summary>
        internal static string AllSkuResponse {
            get {
                return ResourceManager.GetString("AllSkuResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///&quot;errcode&quot;:0,
        ///&quot;errmsg&quot;:&quot;ok&quot;,
        ///&quot;ticket&quot;:&quot;bxLdikRXVbTPdHSM05e5u5sUoXNKdvsdshFKA&quot;,
        ///&quot;expires_in&quot;:7200
        ///} 的本地化字符串。
        /// </summary>
        internal static string ApiTicket {
            get {
                return ResourceManager.GetString("ApiTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 { &quot;card_list&quot;: [
        ///{
        ///&quot;card_id&quot;: &quot;po_2Djks4-yP5PGtgGY4GkbAIIt0&quot;,
        ///&quot;is_succ&quot;: 1
        ///},
        ///{
        ///&quot;card_id&quot;: &quot;po_2Djks4-yP5PGtgGY4GkbAIIt0&quot;,
        ///&quot;is_succ&quot;: 1
        ///},
        ///{
        ///&quot;card_id&quot;: &quot;po_2DjtUhT_i8Q5Hgc0HLkCegYc8&quot;,
        ///&quot;is_succ&quot;: 1
        ///}
        ///]
        ///} 的本地化字符串。
        /// </summary>
        internal static string BatchAddCard {
            get {
                return ResourceManager.GetString("BatchAddCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;xml&gt;
        ///&lt;return_code&gt;&lt;![CDATA[FAIL]]&gt;&lt;/return_code&gt;
        ///&lt;return_msg&gt;&lt;![CDATA[OK]]&gt;&lt;/return_msg&gt;
        ///&lt;/xml&gt; 的本地化字符串。
        /// </summary>
        internal static string BillCheckResponse {
            get {
                return ResourceManager.GetString("BillCheckResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;xml&gt;
        ///&lt;return_code&gt;&lt;![CDATA[SUCCESS]]&gt;&lt;/return_code&gt;
        ///&lt;return_msg&gt;&lt;![CDATA[OK]]&gt;&lt;/return_msg&gt;
        ///&lt;result_code&gt;&lt;![CDATA[FAIL]]&gt;&lt;/result_code&gt;
        ///&lt;err_code&gt;&lt;![CDATA[PAYERROR]]&gt;&lt;/err_code&gt;
        ///&lt;err_code_des&gt;&lt;![CDATA[支付错误]]&gt;&lt;/err_code_des&gt;
        ///&lt;/xml&gt; 的本地化字符串。
        /// </summary>
        internal static string CallToReportResponse {
            get {
                return ResourceManager.GetString("CallToReportResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///&quot;errcode&quot;: 0,
        ///&quot;errmsg&quot;: &quot;ok&quot;,
        ///&quot;card&quot;: {
        ///&quot;card_type&quot;: &quot;GROUPON&quot;,
        ///&quot;groupon&quot;: {
        ///&quot;base_info&quot;: {
        ///&quot;status&quot;: 1,
        ///&quot;id&quot;: &quot;p1Pj9jr90_SQRaVqYI239Ka1erkI&quot;,
        ///&quot;logo_url&quot;:
        ///&quot;http://www.supadmin.cn/uploads/allimg/120216/1_120216214725_1.jpg&quot;,
        ///&quot;appid&quot;: &quot;wx588def6b0089dd48&quot;,
        ///&quot;code_type&quot;: &quot;CODE_TYPE_TEXT&quot;,
        ///&quot;brand_name&quot;: &quot;海底捞&quot;,
        ///&quot;title&quot;: &quot;132 元双人火锅套餐&quot;,
        ///&quot;sub_title&quot;: &quot;hane&quot;,
        ///&quot;date_info&quot;: {
        ///&quot;type&quot;: 1,
        ///&quot;begin_timestamp&quot;: 1397577600,
        ///&quot;end_timestamp&quot;: 1399910400
        ///},
        ///&quot;color&quot;: &quot;#3373bb&quot;,
        ///&quot;notice&quot;: &quot;使用时向服务员出示此券&quot;,
        ///&quot;s [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Card {
            get {
                return ResourceManager.GetString("Card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///&quot;errcode&quot;:0,
        ///&quot;errmsg&quot;:&quot;ok&quot;,
        ///&quot;card_id_list&quot;:[&quot;ph_gmt7cUVrlRk8swPwx7aDyF-pg&quot;],
        ///&quot;total_num&quot;:1 的本地化字符串。
        /// </summary>
        internal static string CardBatch {
            get {
                return ResourceManager.GetString("CardBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///&quot;errcode&quot;:0,
        ///&quot;errmsg&quot;:&quot;ok&quot;,
        ///&quot;result_bonus&quot;: 100,
        ///&quot;result_balance&quot;: 200,
        ///&quot;openid&quot;:&quot;oFS7Fjl0WsZ9AMZqrI80nbIq8xrA&quot;
        ///} 的本地化字符串。
        /// </summary>
        internal static string CardUpdate {
            get {
                return ResourceManager.GetString("CardUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///&quot;err_msg&quot;:&quot; choose_card:ok &quot;,
        ///&quot;choose_card_info&quot;:[
        ///{
        ///&quot;card_id&quot;: &quot;p3G6It08WKRgR0hyV3hHVb6pxrPQ&quot;,
        ///&quot;encrypt_code&quot;:
        ///&quot;XXIzTtMqCxwOaawoE91+VJdsFmv7b8g0VZIZkqf4GWA60Fzpc8ksZ/5ZZ0DVkXdE&quot;}
        ///]
        ///} 的本地化字符串。
        /// </summary>
        internal static string ChooseCard {
            get {
                return ResourceManager.GetString("ChooseCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;xml&gt;
        ///&lt;return_code&gt;&lt;![CDATA[SUCCESS]]&gt;&lt;/return_code&gt;
        ///&lt;return_msg&gt;&lt;![CDATA[OK]]&gt;&lt;/return_msg&gt;
        ///&lt;appid&gt;&lt;![CDATA[wx2421b1c4370ec43b]]&gt;&lt;/appid&gt;
        ///&lt;mch_id&gt;&lt;![CDATA[10000100]]&gt;&lt;/mch_id&gt;
        ///&lt;device_info&gt;&lt;![CDATA[1000]]&gt;&lt;/device_info&gt;
        ///&lt;nonce_str&gt;&lt;![CDATA[sthBJ9QyUG6vkrjJ]]&gt;&lt;/nonce_str&gt;
        ///&lt;sign&gt;&lt;![CDATA[6277A96D7875D4FF23AA7B6A4C3046AB]]&gt;&lt;/sign&gt;
        ///&lt;result_code&gt;&lt;![CDATA[FAIL]]&gt;&lt;/result_code&gt;
        ///&lt;err_code&gt;&lt;![CDATA[PAYERROR]]&gt;&lt;/err_code&gt;
        ///&lt;err_code_des&gt;&lt;![CDATA[支付错误]]&gt;&lt;/err_code_des&gt;
        ///&lt;/xml&gt; 的本地化字符串。
        /// </summary>
        internal static string CloseResponse {
            get {
                return ResourceManager.GetString("CloseResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///&quot;errcode&quot;:0,
        ///&quot;errmsg&quot;:&quot;ok&quot;,
        ///&quot;code&quot;:&quot;751234212312&quot;
        ///} 的本地化字符串。
        /// </summary>
        internal static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///&quot;errcode&quot;:0,
        ///&quot;errmsg&quot;:&quot;ok&quot;,
        ///&quot;openid&quot;:&quot;oFS7Fjl0WsZ9AMZqrI80nbIq8xrA&quot;,
        ///&quot;card&quot;:{
        ///&quot;card_id&quot;:&quot;pFS7Fjg8kV1IdDz01r4SQwMkuCKc&quot;,
        ///&quot;begin_time&quot;: 1404205036,
        ///&quot;end_time&quot;: 1404205036,
        ///}
        ///} 的本地化字符串。
        /// </summary>
        internal static string CodeRes {
            get {
                return ResourceManager.GetString("CodeRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///&quot;errcode&quot;:0,
        ///&quot;errmsg&quot;:&quot;ok&quot;,
        ///&quot;colors&quot;:[
        ///{&quot;name&quot;:&quot;Color010&quot;,&quot;value&quot;:&quot;#55bd47&quot;},
        ///{&quot;name&quot;:&quot;Color020&quot;,&quot;value&quot;:&quot;#10ad61&quot;},
        ///{&quot;name&quot;:&quot;Color030&quot;,&quot;value&quot;:&quot;#35a4de&quot;},
        ///{&quot;name&quot;:&quot;Color040&quot;,&quot;value&quot;:&quot;#3d78da&quot;},
        ///{&quot;name&quot;:&quot;Color050&quot;,&quot;value&quot;:&quot;#9058cb&quot;},
        ///{&quot;name&quot;:&quot;Color060&quot;,&quot;value&quot;:&quot;#de9c33&quot;},
        ///{&quot;name&quot;:&quot;Color070&quot;,&quot;value&quot;:&quot;#ebac16&quot;},
        ///{&quot;name&quot;:&quot;Color080&quot;,&quot;value&quot;:&quot;#f9861f&quot;},
        ///{&quot;name&quot;:&quot;Color081&quot;,&quot;value&quot;:&quot;#f08500&quot;},
        ///{&quot;name&quot;:&quot;Color090&quot;,&quot;value&quot;:&quot;#e75735&quot;},
        ///{&quot;name&quot;:&quot;Color100&quot;,&quot;value&quot;:&quot;#d54036&quot;},
        ///{&quot;name&quot;:&quot;Color101&quot;,&quot;value&quot;... 的本地化字符串。
        /// </summary>
        internal static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///&quot;errcode&quot;:0,
        ///&quot;errmsg&quot;:&quot;ok&quot;,
        ///&quot;card&quot;:{&quot;card_id&quot;:&quot;pFS7Fjg8kV1IdDz01r4SQwMkuCKc&quot;},
        ///&quot;openid&quot;:&quot;oFS7Fjl0WsZ9AMZqrI80nbIq8xrA&quot;
        ///} 的本地化字符串。
        /// </summary>
        internal static string Consume {
            get {
                return ResourceManager.GetString("Consume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;xml&gt;
        ///	&lt;return_code&gt;&lt;![CDATA[SUCCESS]]&gt;&lt;/return_code&gt;
        ///	&lt;return_msg&gt;&lt;![CDATA[OK]]&gt;&lt;/return_msg&gt;
        ///	&lt;appid&gt;&lt;![CDATA[wx2421b1c4370ec43b]]&gt;&lt;/appid&gt;
        ///	&lt;mch_id&gt;&lt;![CDATA[10000100]]&gt;&lt;/mch_id&gt;
        ///	&lt;nonce_str&gt;&lt;![CDATA[sthBJ9QyUG6vkrjJ]]&gt;&lt;/nonce_str&gt;
        ///	&lt;sign&gt;&lt;![CDATA[6277A96D7875D4FF23AA7B6A4C3046AB]]&gt;&lt;/sign&gt;
        ///	&lt;result_code&gt;&lt;![CDATA[FAIL]]&gt;&lt;/result_code&gt;
        ///	&lt;err_code&gt;&lt;![CDATA[PAYERROR]]&gt;&lt;/err_code&gt;
        ///	&lt;short_url&gt;fdasfdaskljklr3w&lt;/short_url&gt;
        ///&lt;/xml&gt; 的本地化字符串。
        /// </summary>
        internal static string ConversionResponse {
            get {
                return ResourceManager.GetString("ConversionResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///  &quot;errcode&quot;: 0,
        ///  &quot;errmsg&quot;: &quot;success&quot;,
        ///  &quot;template_info&quot;: {
        ///    &quot;Id&quot;: 103312916,
        ///    &quot;Name&quot;: &quot;testexpress&quot;,
        ///    &quot;Assumer&quot;: 0,
        ///    &quot;Valuation&quot;: 0,
        ///    &quot;TopFee&quot;: [	
        ///      {
        ///        &quot;Type&quot;: 10000027,
        ///        &quot;Normal&quot;: {
        ///          &quot;StartStandards&quot;: 1,
        ///          &quot;StartFees&quot;: 2,
        ///          &quot;AddStandards&quot;: 3,
        ///          &quot;AddFees&quot;: 1
        ///        },
        ///        &quot;Custom&quot;: [
        ///          {
        ///            &quot;StartStandards&quot;: 1,
        ///            &quot;StartFees&quot;: 1000,
        ///            &quot;AddStandards&quot;: 1,
        ///            &quot;AddFees&quot;: 3 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string IdResponse {
            get {
                return ResourceManager.GetString("IdResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///  &quot;errcode&quot;: 0,
        ///  &quot;errmsg&quot;: &quot;success&quot;,
        ///  &quot;template_info&quot;: {
        ///    &quot;Id&quot;: 103312916,
        ///    &quot;Name&quot;: &quot;testexpress&quot;,
        ///    &quot;Assumer&quot;: 0,
        ///    &quot;Valuation&quot;: 0,
        ///    &quot;TopFee&quot;: [
        ///      {
        ///        &quot;Type&quot;: 10000027,
        ///        &quot;Normal&quot;: {
        ///          &quot;StartStandards&quot;: 1,
        ///          &quot;StartFees&quot;: 2,
        ///          &quot;AddStandards&quot;: 3,
        ///          &quot;AddFees&quot;: 1
        ///        },
        ///        &quot;Custom&quot;: [
        ///          {
        ///            &quot;StartStandards&quot;: 1,
        ///            &quot;StartFees&quot;: 1000,
        ///            &quot;AddStandards&quot;: 1,
        ///            &quot;AddFees&quot;: 3, [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string IdTemplateResponse {
            get {
                return ResourceManager.GetString("IdTemplateResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///	&quot;errcode&quot;: 0,
        ///	&quot;errmsg&quot;: &quot;success&quot;,
        ///	&quot;order&quot;: {
        ///		&quot;order_id&quot;: &quot;7197417460812533543&quot;,
        ///		&quot;order_status&quot;: 6,
        ///		&quot;order_total_price&quot;: 6,
        ///		&quot;order_create_time&quot;: 1394635817,
        ///		&quot;order_express_price&quot;: 5,
        ///		&quot;buyer_openid&quot;: &quot;oDF3iY17NsDAW4UP2qzJXPsz1S9Q&quot;,
        ///		&quot;buyer_nick&quot;: &quot;likeacat&quot;,
        ///		&quot;receiver_name&quot;: &quot;张小猫&quot;,
        ///		&quot;receiver_province&quot;: &quot;广东省&quot;,
        ///		&quot;receiver_city&quot;: &quot;广州市&quot;,
        ///&quot;receiver_zone&quot;: &quot;天河区&quot;,
        ///		&quot;receiver_address&quot;: &quot;华景路一号南方通信大厦5楼&quot;,
        ///		&quot;receiver_mobile&quot;: &quot;123456789&quot;,
        ///		&quot;receiver_phone&quot;: &quot;123456789&quot;,
        ///		&quot;pro [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string IdToBillResponse {
            get {
                return ResourceManager.GetString("IdToBillResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///	&quot;errcode&quot;: 0,
        ///	&quot;errmsg&quot;: &quot;success&quot;,
        ///	&quot;group_detail&quot;: {
        ///		&quot;group_id&quot;: 200077549,
        ///		&quot;group_name&quot;: &quot;最新上架&quot;,
        ///		&quot;product_list&quot;: [
        ///		  &quot;pDF3iYzZoY-Budrzt8O6IxrwIJAA&quot;,
        ///		  &quot;pDF3iY3pnWSGJcO2MpS2Nxy3HWx8&quot;,
        ///		  &quot;pDF3iY33jNt0Dj3M3UqiGlUxGrio&quot;
        ///		]
        ///	}
        ///} 的本地化字符串。
        /// </summary>
        internal static string IdToResponse {
            get {
                return ResourceManager.GetString("IdToResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///&quot;errcode&quot;:0,
        ///&quot;errmsg&quot;:&quot;ok&quot;,
        ///&quot;location_id_list&quot;:[271262077,271262079]
        ///} 的本地化字符串。
        /// </summary>
        internal static string LocationBatchAddResult {
            get {
                return ResourceManager.GetString("LocationBatchAddResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 { &quot;errcode&quot;: 0,
        ///&quot;errmsg&quot;: &quot;ok&quot;,
        ///&quot;location_list&quot;: [
        ///{
        ///&quot;location_id&quot;: &quot;493&quot;,
        ///&quot;business_name&quot;: &quot;steventao home&quot;,
        ///&quot;phone&quot;: &quot;020-12345678&quot;,
        ///&quot;address&quot;: &quot;广东省广州市番禺区广东省广州市番禺区南浦大道&quot;,
        ///&quot;longitude&quot;: 113.280212402,
        ///&quot;latitude&quot;: 23.0350666046
        ///},
        ///{
        ///&quot;location_id&quot;: &quot;468&quot;,
        ///&quot;business_name&quot;: &quot;TIT 创意园B4&quot;,
        ///&quot;phone&quot;: &quot;020-12345678&quot;,
        ///&quot;address&quot;: &quot;广东省广州市海珠区&quot;,
        ///&quot;longitude&quot;: 113.325248718,
        ///&quot;latitude&quot;: 23.1008300781
        ///}
        ///],
        ///&quot;count&quot;: 2
        ///} 的本地化字符串。
        /// </summary>
        internal static string LocationBatchGetResult {
            get {
                return ResourceManager.GetString("LocationBatchGetResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;xml&gt;
        ///&lt;return_code&gt;&lt;![CDATA[SUCCESS]]&gt;&lt;/return_code&gt;
        ///&lt;return_msg&gt;&lt;![CDATA[OK]]&gt;&lt;/return_msg&gt;
        ///&lt;appid&gt;&lt;![CDATA[wx2421b1c4370ec43b]]&gt;&lt;/appid&gt;
        ///&lt;mch_id&gt;&lt;![CDATA[10000100]]&gt;&lt;/mch_id&gt;
        ///&lt;device_info&gt;&lt;![CDATA[1000]]&gt;&lt;/device_info&gt;
        ///&lt;nonce_str&gt;&lt;![CDATA[FvYSnPuFFPkAr77M]]&gt;&lt;/nonce_str&gt;
        ///&lt;sign&gt;&lt;![CDATA[63238039D6E43634297CF2A6EB5F3B72]]&gt;&lt;/sign&gt;
        ///&lt;result_code&gt;&lt;![CDATA[SUCCESS]]&gt;&lt;/result_code&gt;
        ///&lt;err_code&gt;&lt;![CDATA[PAYERROR]]&gt;&lt;/err_code&gt;
        ///&lt;err_code_des&gt;&lt;![CDATA[支付错误]]&gt;&lt;/err_code_des&gt;
        ///&lt;openid&gt;&lt;![CDATA[oUpF8uN95-Ptaags6E [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string MicroPayResponse {
            get {
                return ResourceManager.GetString("MicroPayResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///	&quot;errcode&quot;: 0,
        ///	&quot;errmsg&quot;: &quot;success&quot;,
        ///	&quot;shelf_info&quot;: {
        ///		&quot;module_infos&quot;: [
        ///             {
        ///		  &quot;group_info&quot;: {
        ///			&quot;filter&quot;: {
        ///			  &quot;count&quot;: 2
        ///			},
        ///			&quot;group_id&quot;: 50
        ///		  },
        ///		  &quot;eid&quot;: 1
        ///		},
        ///		{
        ///			&quot;group_infos&quot;: {
        ///				&quot;groups&quot;: [
        ///				  {
        ///					&quot;group_id&quot;: 49
        ///				  },
        ///				  {
        ///					&quot;group_id&quot;: 50
        ///				  },
        ///				  {
        ///					&quot;group_id&quot;: 51
        ///				  }
        ///				]
        ///		  },
        ///		  &quot;eid&quot;: 2
        ///		},
        ///		{
        ///		  &quot;group_info&quot;: {
        ///			&quot;group_id&quot;: 52,
        ///			&quot;img&quot;: &quot;http://mmbiz.qpic.cn/mmbiz/4whpV1VZl29nqqObBwFwnIX3li [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string ModuleInfos {
            get {
                return ResourceManager.GetString("ModuleInfos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;xml&gt;
        ///&lt;return_code&gt;&lt;![CDATA[SUCCESS]]&gt;&lt;/return_code&gt;
        ///&lt;return_msg&gt;&lt;![CDATA[OK]]&gt;&lt;/return_msg&gt;
        ///&lt;appid&gt;&lt;![CDATA[wx2421b1c4370ec43b]]&gt;&lt;/appid&gt;
        ///&lt;mch_id&gt;&lt;![CDATA[10000100]]&gt;&lt;/mch_id&gt;
        ///&lt;nonce_str&gt;&lt;![CDATA[sthBJ9QyUG6vkrjJ]]&gt;&lt;/nonce_str&gt;
        ///&lt;prepay_id&gt;zengyudanXPY&lt;/prepay_id&gt;
        ///&lt;sign&gt;&lt;![CDATA[6277A96D7875D4FF23AA7B6A4C3046AB]]&gt;&lt;/sign&gt;
        ///&lt;result_code&gt;&lt;![CDATA[FAIL]]&gt;&lt;/result_code&gt;
        ///&lt;err_code_des&gt;&lt;![CDATA[支付错误]]&gt;&lt;/err_code_des&gt;
        ///&lt;/xml&gt; 的本地化字符串。
        /// </summary>
        internal static string NativeResponse {
            get {
                return ResourceManager.GetString("NativeResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;xml&gt;
        ///&lt;return_code&gt;&lt;![CDATA[SUCCESS]]&gt;&lt;/return_code&gt;
        ///&lt;return_msg&gt;&lt;![CDATA[OK]]&gt;&lt;/return_msg&gt;
        ///&lt;appid&gt;&lt;![CDATA[wx2421b1c4370ec43b]]&gt;&lt;/appid&gt;
        ///&lt;mch_id&gt;&lt;![CDATA[10000100]]&gt;&lt;/mch_id&gt;
        ///&lt;device_info&gt;&lt;![CDATA[1000]]&gt;&lt;/device_info&gt;
        ///&lt;nonce_str&gt;&lt;![CDATA[FvYSnPuFFPkAr77M]]&gt;&lt;/nonce_str&gt;
        ///&lt;sign&gt;&lt;![CDATA[63238039D6E43634297CF2A6EB5F3B72]]&gt;&lt;/sign&gt;
        ///&lt;result_code&gt;&lt;![CDATA[SUCCESS]]&gt;&lt;/result_code&gt;
        ///&lt;err_code&gt;&lt;![CDATA[PAYERROR]]&gt;&lt;/err_code&gt;
        ///&lt;err_code_des&gt;&lt;![CDATA[支付错误]]&gt;&lt;/err_code_des&gt;
        ///&lt;openid&gt;&lt;![CDATA[oUpF8uN95-Ptaags6E [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string NoticeResponse {
            get {
                return ResourceManager.GetString("NoticeResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;xml&gt;
        ///&lt;return_code&gt;&lt;![CDATA[SUCCESS]]&gt;&lt;/return_code&gt;
        ///&lt;return_msg&gt;&lt;![CDATA[OK]]&gt;&lt;/return_msg&gt;
        ///&lt;appid&gt;&lt;![CDATA[wx2421b1c4370ec43b]]&gt;&lt;/appid&gt;
        ///&lt;mch_id&gt;&lt;![CDATA[10000100]]&gt;&lt;/mch_id&gt;
        ///&lt;device_info&gt;&lt;![CDATA[1000]]&gt;&lt;/device_info&gt;
        ///&lt;nonce_str&gt;&lt;![CDATA[FvYSnPuFFPkAr77M]]&gt;&lt;/nonce_str&gt;
        ///&lt;sign&gt;&lt;![CDATA[63238039D6E43634297CF2A6EB5F3B72]]&gt;&lt;/sign&gt;
        ///&lt;result_code&gt;&lt;![CDATA[SUCCESS]]&gt;&lt;/result_code&gt;
        ///&lt;err_code&gt;&lt;![CDATA[PAYERROR]]&gt;&lt;/err_code&gt;
        ///&lt;err_code_des&gt;&lt;![CDATA[支付错误]]&gt;&lt;/err_code_des&gt;
        ///&lt;trade_state&gt;&lt;![CDATA[REFUND]]&gt;&lt;/tr [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string OrderQueryResponse {
            get {
                return ResourceManager.GetString("OrderQueryResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;xml&gt;
        ///	&lt;return_code&gt;&lt;![CDATA[SUCCESS]]&gt;&lt;/return_code&gt;
        ///	&lt;return_msg&gt;&lt;![CDATA[OK]]&gt;&lt;/return_msg&gt;
        ///	&lt;appid&gt;&lt;![CDATA[wx2421b1c4370ec43b]]&gt;&lt;/appid&gt;
        ///	&lt;mch_id&gt;&lt;![CDATA[10000100]]&gt;&lt;/mch_id&gt;
        ///	&lt;device_info&gt;&lt;![CDATA[1000]]&gt;&lt;/device_info&gt;
        ///	&lt;nonce_str&gt;&lt;![CDATA[sthBJ9QyUG6vkrjJ]]&gt;&lt;/nonce_str&gt;
        ///	&lt;sign&gt;&lt;![CDATA[6277A96D7875D4FF23AA7B6A4C3046AB]]&gt;&lt;/sign&gt;
        ///	&lt;result_code&gt;&lt;![CDATA[FAIL]]&gt;&lt;/result_code&gt;
        ///	&lt;err_code&gt;&lt;![CDATA[PAYERROR]]&gt;&lt;/err_code&gt;
        ///	&lt;err_code_des&gt;&lt;![CDATA[支付错误]]&gt;&lt;/err_code_des&gt;
        ///	&lt;trade_type&gt;NATIVE&lt;/trade_t [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string PaymentResponse {
            get {
                return ResourceManager.GetString("PaymentResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///	&quot;errcode&quot;: 0,
        ///	&quot;errmsg&quot;: &quot;success&quot;,
        ///	&quot;product_info&quot;: {
        ///		&quot;product_id&quot;: &quot;pDF3iY6Kr_BV_CXaiYysoGqJhppQ&quot;,
        ///		&quot;product_base&quot;: {
        ///			&quot;name&quot;: &quot;testaddproduct&quot;,
        ///			&quot;category_id&quot;: [	
        ///				537074298
        ///			],
        ///			&quot;img&quot;: [
        ///				&quot;http://mmbiz.qpic.cn/mmbiz/4whpV1VZl2iccsvYbHvnphkyGtnvjD3ulEKogfsiaua49pvLfUS8Ym0GSYjViaLic0FD3vN0V8PILcibEGb2fPfEOmw/0&quot;
        ///			],
        ///			&quot;property&quot;: [
        ///				{
        ///					&quot;id&quot;: &quot;品牌&quot;,
        ///					&quot;vid&quot;: &quot;Fujifilm/富士&quot;
        ///				},
        ///				{
        ///					&quot;id&quot;: &quot;屏幕尺寸&quot;,
        ///					&quot;vid&quot;: &quot;1.8英寸&quot;
        ///				},
        ///				{
        ///					&quot;id&quot;: &quot;防抖性能&quot; [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string QueryResponse {
            get {
                return ResourceManager.GetString("QueryResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;xml&gt;
        ///&lt;return_code&gt;&lt;![CDATA[SUCCESS]]&gt;&lt;/return_code&gt;
        ///&lt;return_msg&gt;&lt;![CDATA[OK]]&gt;&lt;/return_msg&gt;
        ///&lt;appid&gt;&lt;![CDATA[wx2421b1c4370ec43b]]&gt;&lt;/appid&gt;
        ///&lt;mch_id&gt;&lt;![CDATA[10000100]]&gt;&lt;/mch_id&gt;
        ///&lt;device_info&gt;&lt;![CDATA[1000]]&gt;&lt;/device_info&gt;
        ///&lt;nonce_str&gt;&lt;![CDATA[FvYSnPuFFPkAr77M]]&gt;&lt;/nonce_str&gt;
        ///&lt;sign&gt;&lt;![CDATA[63238039D6E43634297CF2A6EB5F3B72]]&gt;&lt;/sign&gt;
        ///&lt;result_code&gt;&lt;![CDATA[SUCCESS]]&gt;&lt;/result_code&gt;
        ///&lt;transaction_id&gt;&lt;![CDATA[1008450740201407220000058756]]&gt;&lt;/transaction_id&gt;
        ///&lt;out_trade_no&gt;&lt;![CDATA[1406033828]]&gt;&lt;/out_trade_no [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string RefundApplicationResponse {
            get {
                return ResourceManager.GetString("RefundApplicationResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;xml&gt;
        ///&lt;return_code&gt;&lt;![CDATA[SUCCESS]]&gt;&lt;/return_code&gt;
        ///&lt;return_msg&gt;&lt;![CDATA[OK]]&gt;&lt;/return_msg&gt;
        ///&lt;appid&gt;&lt;![CDATA[wx2421b1c4370ec43b]]&gt;&lt;/appid&gt;
        ///&lt;mch_id&gt;&lt;![CDATA[10000100]]&gt;&lt;/mch_id&gt;
        ///&lt;device_info&gt;&lt;![CDATA[1000]]&gt;&lt;/device_info&gt;
        ///&lt;nonce_str&gt;&lt;![CDATA[FvYSnPuFFPkAr77M]]&gt;&lt;/nonce_str&gt;
        ///&lt;sign&gt;&lt;![CDATA[63238039D6E43634297CF2A6EB5F3B72]]&gt;&lt;/sign&gt;
        ///&lt;result_code&gt;&lt;![CDATA[SUCCESS]]&gt;&lt;/result_code&gt;
        ///&lt;transaction_id&gt;&lt;![CDATA[1008450740201407220000058756]]&gt;&lt;/transaction_id&gt;
        ///&lt;out_trade_no&gt;&lt;![CDATA[1406033828]]&gt;&lt;/out_trade_no [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string RefundInquiryResponse {
            get {
                return ResourceManager.GetString("RefundInquiryResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;xml&gt;
        ///&lt;return_code&gt;&lt;![CDATA[SUCCESS]]&gt;&lt;/return_code&gt;
        ///&lt;return_msg&gt;&lt;![CDATA[OK]]&gt;&lt;/return_msg&gt;
        ///&lt;appid&gt;&lt;![CDATA[wx2421b1c4370ec43b]]&gt;&lt;/appid&gt;
        ///&lt;mch_id&gt;&lt;![CDATA[10000100]]&gt;&lt;/mch_id&gt;
        ///&lt;device_info&gt;&lt;![CDATA[1000]]&gt;&lt;/device_info&gt;
        ///&lt;nonce_str&gt;&lt;![CDATA[sthBJ9QyUG6vkrjJ]]&gt;&lt;/nonce_str&gt;
        ///&lt;sign&gt;&lt;![CDATA[6277A96D7875D4FF23AA7B6A4C3046AB]]&gt;&lt;/sign&gt;
        ///&lt;result_code&gt;&lt;![CDATA[FAIL]]&gt;&lt;/result_code&gt;
        ///&lt;err_code&gt;&lt;![CDATA[PAYERROR]]&gt;&lt;/err_code&gt;
        ///&lt;err_code_des&gt;&lt;![CDATA[支付错误]]&gt;&lt;/err_code_des&gt;
        ///&lt;recall&gt;Y&lt;/recall&gt;
        ///&lt;/xml&gt; 的本地化字符串。
        /// </summary>
        internal static string ReverseResponse {
            get {
                return ResourceManager.GetString("ReverseResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;xml&gt;
        ///&lt;return_code&gt;&lt;![CDATA[SUCCESS]]&gt;&lt;/return_code&gt;
        ///&lt;return_msg&gt;&lt;![CDATA[OK]]&gt;&lt;/return_msg&gt;
        ///&lt;appid&gt;&lt;![CDATA[wx2421b1c4370ec43b]]&gt;&lt;/appid&gt;
        ///&lt;mch_id&gt;&lt;![CDATA[10000100]]&gt;&lt;/mch_id&gt;
        ///&lt;device_info&gt;&lt;![CDATA[1000]]&gt;&lt;/device_info&gt;
        ///&lt;nonce_str&gt;&lt;![CDATA[FvYSnPuFFPkAr77M]]&gt;&lt;/nonce_str&gt;
        ///&lt;sign&gt;&lt;![CDATA[63238039D6E43634297CF2A6EB5F3B72]]&gt;&lt;/sign&gt;
        ///&lt;result_code&gt;&lt;![CDATA[SUCCESS]]&gt;&lt;/result_code&gt;
        ///&lt;err_code&gt;&lt;![CDATA[PAYERROR]]&gt;&lt;/err_code&gt;
        ///&lt;err_code_des&gt;&lt;![CDATA[支付错误]]&gt;&lt;/err_code_des&gt;
        ///&lt;trade_state&gt;&lt;![CDATA[REFUND]]&gt;&lt;/tr [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string SeachResponse {
            get {
                return ResourceManager.GetString("SeachResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///  &quot;errcode&quot;: 0,
        ///  &quot;errmsg&quot;: &quot;success&quot;,
        ///  &quot;products_info&quot;: [
        ///    {
        ///      &quot;product_base&quot;: ..., 
        ///      &quot;sku_list&quot;: ..., 
        ///  &quot;attrext&quot;: ..., 
        ///      &quot;delivery_info&quot;: ..., 
        ///      &quot;product_id&quot;: &quot;pDF3iY-mql6CncpbVajaB_obC3Bk&quot;,
        ///      &quot;status&quot;: 1
        ///    },
        ///    {
        ///      &quot;product_base&quot;: ..., 
        ///      &quot;sku_list&quot;: ..., 
        ///  &quot;attrext&quot;: ..., 
        ///      &quot;delivery_info&quot;: ..., 
        ///      &quot;product_id&quot;: &quot;pDF3iY-mql6CncpbVajaB_obC321&quot;,
        ///      &quot;status&quot;: 1
        ///    }
        ///  ]
        ///} 的本地化字符串。
        /// </summary>
        internal static string StatusGoodResponse {
            get {
                return ResourceManager.GetString("StatusGoodResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///	&quot;errcode&quot;: 0,
        ///	&quot;errmsg&quot;: &quot;success&quot;,
        ///	&quot;order_list&quot;: [
        ///		{
        ///		  &quot;order_id&quot;: &quot;7197417460812533543&quot;,
        ///		  &quot;order_status&quot;: 6,
        ///		  &quot;order_total_price&quot;: 6,
        ///		  &quot;order_create_time&quot;: 1394635817,
        ///		  &quot;order_express_price&quot;: 5,
        ///		  &quot;buyer_openid&quot;: &quot;oDF3iY17NsDAW4UP2qzJXPsz1S9Q&quot;,
        ///		  &quot;buyer_nick&quot;: &quot;likeacat&quot;,
        ///		  &quot;receiver_name&quot;: &quot;张小猫&quot;,
        ///		  &quot;receiver_province&quot;: &quot;广东省&quot;,
        ///		  &quot;receiver_city&quot;: &quot;广州市&quot;,
        ///		  &quot;receiver_address&quot;: &quot;华景路一号南方通信大厦5楼&quot;,
        ///		  &quot;receiver_mobile&quot;: &quot;123456&quot;,
        ///		  &quot;receiver_phone&quot;: &quot;123456&quot;,
        ///	 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string StatusToBillResponse {
            get {
                return ResourceManager.GetString("StatusToBillResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 } 的本地化字符串。
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///  &quot;errcode&quot;: 0,
        ///  &quot;errmsg&quot;: &quot;success&quot;,
        ///  &quot;cate_list&quot;: [
        ///    {
        ///      &quot;id&quot;: &quot;537074292&quot;,
        ///      &quot;name&quot;: &quot;数码相机&quot;
        ///    },
        ///    {
        ///      &quot;id&quot;: &quot;537074293&quot;,
        ///      &quot;name&quot;: &quot;家用摄像机&quot;
        ///    },
        ///    {
        ///      &quot;id&quot;: &quot;537074298&quot;,
        ///      &quot;name&quot;: &quot;单反相机&quot;
        ///    },
        ///    {
        ///      &quot;id&quot;: &quot;537082412&quot;,
        ///      &quot;name&quot;: &quot;镜头&quot;
        ///    },
        ///    {
        ///      &quot;id&quot;: &quot;537102001&quot;,
        ///      &quot;name&quot;: &quot;单电/微单&quot;
        ///    }
        ///  ]
        ///} 的本地化字符串。
        /// </summary>
        internal static string SubGoodResponse {
            get {
                return ResourceManager.GetString("SubGoodResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///&quot;errcode&quot;:0,
        ///&quot;errmsg&quot;:&quot;ok&quot;,
        ///&quot;ticket&quot;:&quot;gQG28DoAAAAAAAAAASxodHRwOi8vd2VpeGluLnFxLmNvbS9xL0FuWC1DNmZuVEhv
        ///MVp4NDNMRnNRAAIEesLvUQMECAcAAA==&quot;
        ///} 的本地化字符串。
        /// </summary>
        internal static string Ticket {
            get {
                return ResourceManager.GetString("Ticket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///	&quot;errcode&quot;: 0,
        ///	&quot;errmsg&quot;: &quot;success&quot;,
        ///
        ///		  &quot;shelf_info&quot;: {
        ///			&quot;module_infos&quot;: [
        ///			  {
        ///
        ///  &quot;group_info&quot;: {
        ///	&quot;filter&quot;: {
        ///	  &quot;count&quot;: 4
        ///	},
        ///	&quot;group_id&quot;: 50
        ///  },
        ///  &quot;eid&quot;: 1
        ///},
        ///{
        ///	&quot;group_infos&quot;: {
        ///		&quot;groups&quot;: [
        ///		  {
        ///			&quot;group_id&quot;: 49
        ///		  },
        ///		  {
        ///			&quot;group_id&quot;: 50
        ///		  },
        ///		  {
        ///			&quot;group_id&quot;: 51
        ///		  }
        ///		]
        ///  },
        ///  &quot;eid&quot;: 2
        ///},
        ///{
        ///  &quot;group_info&quot;: {
        ///	&quot;group_id&quot;: 52,
        ///	&quot;img&quot;: &quot;http://mmbiz.qpic.cn/mmbiz/4whpV1VZl29nqqObBwFwnIX3licVPnFV5Jm64z4I0TTicv0TjN7Vl9bykUUibYKIOjicAwIt6Oy0Y6a1Rj [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string WeShelf {
            get {
                return ResourceManager.GetString("WeShelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///	&quot;errcode&quot;: 0,
        ///	&quot;errmsg&quot;: &quot;success&quot;,
        ///	&quot;shelves&quot;: [
        ///		{
        ///		  &quot;shelf_info&quot;: {
        ///			&quot;module_infos&quot;: [
        ///			  {
        ///				&quot;group_infos&quot;: {
        ///				  &quot;groups&quot;: [
        ///					{
        ///					  &quot;group_id&quot;: 200080093
        ///					},
        ///					{
        ///					  &quot;group_id&quot;: 200080118
        ///					},
        ///					{
        ///					  &quot;group_id&quot;: 200080119
        ///					},
        ///					{
        ///					  &quot;group_id&quot;: 200080135
        ///					}
        ///				  ],
        ///				  &quot;img_background&quot;: &quot;http://mmbiz.qpic.cn/mmbiz/4whpV1VZl294FzPwnf9dAcaN7ButStztAZyy2yHY8pW6sTQKicIhAy5F0a2CqmrvDBjMFLtc2aEhAQ7uHsPow9A/0&quot;
        ///				},
        ///				&quot;eid&quot; [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string WeShelves {
            get {
                return ResourceManager.GetString("WeShelves", resourceCulture);
            }
        }
    }
}
