//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YJC.Toolkit.Razor.Dynamic {
    using System;
    using System.Text;
    using System.Collections.Generic;
    using System.Linq;
    using System.IO;
    using YJC.Toolkit.Razor;
    using YJC.Toolkit.Web;
    using YJC.Toolkit.MetaData;
    using YJC.Toolkit.Data;
    using YJC.Toolkit.Sys;
    
    
    public class dgitzhoumituservertestmanagewebxmlrazorusermanagerlogoncshtml : YJC.Toolkit.Razor.NormalCustomTemplate {
        
#line hidden
            
    string GetJson(Tk5NormalTableData table)
    {
        var json = string.Format("{{\"Tables\":[{0}]}}", table.JsonFields);
        return StringUtil.EscapeHtmlAttribute(json);
    } 

        
        public dgitzhoumituservertestmanagewebxmlrazorusermanagerlogoncshtml() {
        }
        
        public override void Execute() {
  
    Tk5NormalTableData table = ViewBag.MetaData.Table;
    IEnumerable<Tk5FieldInfoEx> list = table.TableList;
    ObjectContainer receiver = Model.Object;

WriteLiteral("\r\n");

WriteLiteral("<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    <title>");

      Write(ViewBag.Title);

WriteLiteral("</title>\r\n    <meta");

WriteLiteral(" http-equiv=\"X-UA-Compatible\"");

WriteLiteral(" content=\"IE=edge\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" http-equiv=\"Content-Type\"");

WriteLiteral(" content=\"text/html; charset=utf-8\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable" +
"=0;\"");

WriteLiteral(" />\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteAttribute("href", Tuple.Create(" href=\"", 917), Tuple.Create("\"", 990)
, Tuple.Create(Tuple.Create("", 924), Tuple.Create<System.Object, System.Int32>("toolkitjs/v5/bootstrap/css/bootstrap.min.css".AppVirutalPath()
, 924), false)
);

WriteLiteral(" />\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1038), Tuple.Create("\"", 1097)
, Tuple.Create(Tuple.Create("", 1045), Tuple.Create<System.Object, System.Int32>("usercss/UserManager/signin.css".AppVirutalPath()
, 1045), false)
);

WriteLiteral(" />\r\n</head>\r\n<body");

WriteLiteral(" data-webPath=\"");

               Write(HtmlUtil.AppVirtualPath);

WriteLiteral("\"");

WriteLiteral(" id=\"WebInsertXmlPage\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"container-fluid\"");

WriteLiteral(">\r\n        <form");

WriteLiteral(" action=\".\"");

WriteLiteral(" class=\"form-signin\"");

WriteLiteral(" role=\"form\"");

WriteLiteral(" id=\"PostForm\"");

WriteLiteral(" data-post=\"");

                                                                             Write(GetJson(table));

WriteLiteral("\"");

WriteLiteral(" >\r\n            <h2");

WriteLiteral(" class=\"form-signin-heading\"");

WriteLiteral(">请登录系统</h2>\r\n            <div");

WriteAttribute("id", Tuple.Create(" id=\"", 1391), Tuple.Create("\"", 1412)
, Tuple.Create(Tuple.Create("", 1396), Tuple.Create<System.Object, System.Int32>(table.TableName
, 1396), false)
);

WriteLiteral(" class=\"tk-datatable table-row\"");

WriteLiteral(">\r\n");

                
                 foreach (Tk5FieldInfoEx field in list)
                {

WriteLiteral("                    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                        <span");

WriteLiteral(" class=\"tk-control\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

                       Write(field.Control(receiver, null, true));

WriteLiteral("\r\n                        </span>\r\n                    </div>\r\n");

                }

WriteLiteral("            </div>\r\n            <button");

WriteLiteral(" class=\"btn btn-lg btn-primary btn-block btn-submit\"");

WriteLiteral(">登录</button>\r\n        </form>\r\n    </div>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 1934), Tuple.Create("\"", 1999)
, Tuple.Create(Tuple.Create("", 1940), Tuple.Create<System.Object, System.Int32>("toolkitjs/v5/lib/jquery-1.11.1.min.js".AppVirutalPath()
, 1940), false)
);

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 2046), Tuple.Create("\"", 2116)
, Tuple.Create(Tuple.Create("", 2052), Tuple.Create<System.Object, System.Int32>("toolkitjs/v5/bootstrap/js/bootstrap.min.js".AppVirutalPath()
, 2052), false)
);

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 2163), Tuple.Create("\"", 2222)
, Tuple.Create(Tuple.Create("", 2169), Tuple.Create<System.Object, System.Int32>("toolkitjs/v5/toolkit/toolkit.js".AppVirutalPath()
, 2169), false)
);

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 2269), Tuple.Create("\"", 2339)
, Tuple.Create(Tuple.Create("", 2275), Tuple.Create<System.Object, System.Int32>("toolkitjs/v5/toolkit/coreT/toolkit.page.js".AppVirutalPath()
, 2275), false)
);

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 2386), Tuple.Create("\"", 2460)
, Tuple.Create(Tuple.Create("", 2392), Tuple.Create<System.Object, System.Int32>("toolkitjs/v5/toolkit/coreT/toolkit.data.js?v=5".AppVirutalPath()
, 2392), false)
);

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 2507), Tuple.Create("\"", 2575)
, Tuple.Create(Tuple.Create("", 2513), Tuple.Create<System.Object, System.Int32>("toolkitjs/v5/toolkit/coreT/toolkit.ui.js".AppVirutalPath()
, 2513), false)
);

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 2622), Tuple.Create("\"", 2692)
, Tuple.Create(Tuple.Create("", 2628), Tuple.Create<System.Object, System.Int32>("toolkitjs/v5/toolkit/coreT/toolkit.edit.js".AppVirutalPath()
, 2628), false)
);

WriteLiteral("> </script>\r\n</body>\r\n</html>\r\n");

        }
    }
}
