//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YJC.Toolkit.Razor.Dynamic {
    using System;
    using System.Text;
    using System.Collections.Generic;
    using System.Linq;
    using System.IO;
    using YJC.Toolkit.Razor;
    using YJC.Toolkit.Web;
    using YJC.Toolkit.Sys;
    
    
    public class dmituservertestmanagewebxmlrazortemplatebootcssbincsscshtml : YJC.Toolkit.Razor.NormalDetailTemplate {
        
#line hidden
        
        public dmituservertestmanagewebxmlrazortemplatebootcssbincsscshtml() {
        }
        
        public override void Execute() {
WriteLiteral("<link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteAttribute("href", Tuple.Create(" href=\"", 63), Tuple.Create("\"", 136)
, Tuple.Create(Tuple.Create("", 70), Tuple.Create<System.Object, System.Int32>("toolkitjs/v5/bootstrap/css/bootstrap.min.css".AppVirutalPath()
, 70), false)
);

WriteLiteral(" />\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteAttribute("href", Tuple.Create(" href=\"", 184), Tuple.Create("\"", 263)
, Tuple.Create(Tuple.Create("", 191), Tuple.Create<System.Object, System.Int32>("toolkitjs/v5/bootstrap/css/bootstrap-theme.min.css".AppVirutalPath()
, 191), false)
);

WriteLiteral(" />\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteAttribute("href", Tuple.Create(" href=\"", 311), Tuple.Create("\"", 387)
, Tuple.Create(Tuple.Create("", 318), Tuple.Create<System.Object, System.Int32>("toolkitjs/v5/bootstrap/css/font-awesome.min.css".AppVirutalPath()
, 318), false)
);

WriteLiteral(" />\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteAttribute("href", Tuple.Create(" href=\"", 435), Tuple.Create("\"", 495)
, Tuple.Create(Tuple.Create("", 442), Tuple.Create<System.Object, System.Int32>("toolkitcss/v5/commonM/style.css".AppVirutalPath()
, 442), false)
);

WriteLiteral(" />");

        }
    }
}
