//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YJC.Toolkit.Razor.Dynamic {
    using System;
    using System.Text;
    using System.Collections.Generic;
    using System.Linq;
    using System.IO;
    using YJC.Toolkit.Razor;
    using YJC.Toolkit.Web;
    using System.Data;
    using System.Web;
    using YJC.Toolkit.Sys;
    
    
    public class drepgitmanagermituworkmituservertestmanagewebxmlrazortemplatebootcsseasysearchtreetemplatecshtml : YJC.Toolkit.Razor.NormalCustomTemplate {
        
#line hidden
            
    string GetUrl(Dictionary<string, string> queryString) {
        string url = "Library/WebModuleContentPage.tkx?Source=EasySearchTree&amp;useSource=true&amp;RegName=" + queryString["RegName"];
        return url.AppVirutalPath();
    }

        
        public drepgitmanagermituworkmituservertestmanagewebxmlrazortemplatebootcsseasysearchtreetemplatecshtml() {
        }
        
        public override void Execute() {
  
    Dictionary<string, string> queryString = Model.QueryString;

WriteLiteral("\r\n");

WriteLiteral("<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    <title>");

      Write(ViewBag.Title);

WriteLiteral("</title>\r\n    <meta");

WriteLiteral(" http-equiv=\"X-UA-Compatible\"");

WriteLiteral(" content=\"IE=edge\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" http-equiv=\"Content-Type\"");

WriteLiteral(" content=\"text/html; charset=utf-8\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable" +
"=0;\"");

WriteLiteral(" />\r\n");

WriteLiteral("    ");

Write(RenderLayoutPartial("../bin/css.cshtml", null));

WriteLiteral("\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteAttribute("href", Tuple.Create(" href=\"", 914), Tuple.Create("\"", 991)
, Tuple.Create(Tuple.Create("", 921), Tuple.Create<System.Object, System.Int32>("toolkitjs/v5/jstree/themes/default/style.min.css".AppVirutalPath()
, 921), false)
);

WriteLiteral(" />\r\n</head>\r\n<body");

WriteLiteral(" class=\"tk-dataPage\"");

WriteLiteral(" data-webPath=\"");

                                   Write(HtmlUtil.AppVirtualPath);

WriteLiteral("\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"container-fluid\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"tktree w100p h100p oa\"");

WriteLiteral(" data-url=\"");

                                                Write(GetUrl(queryString));

WriteLiteral("\"");

WriteLiteral(" data-selectFunc=\"Toolkit.ui.easySearchDialogTreeClick\"");

WriteLiteral(" data-initValue=\"");

                                                                                                                                             Write(queryString.GetKeyValue("InitValue"));

WriteLiteral("\"");

WriteLiteral(">\r\n        </div>\r\n    </div>\r\n");

WriteLiteral("    ");

Write(RenderLayoutPartial("../bin/js.cshtml", null));

WriteLiteral("\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 1410), Tuple.Create("\"", 1467)
, Tuple.Create(Tuple.Create("", 1416), Tuple.Create<System.Object, System.Int32>("toolkitjs/v5/jstree/jstree.js".AppVirutalPath()
, 1416), false)
);

WriteLiteral("> </script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 1515), Tuple.Create("\"", 1585)
, Tuple.Create(Tuple.Create("", 1521), Tuple.Create<System.Object, System.Int32>("toolkitjs/v5/toolkit/coreT/toolkit.tree.js".AppVirutalPath()
, 1521), false)
);

WriteLiteral("> </script>\r\n</body>\r\n</html>\r\n");

        }
    }
}
