//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YJC.Toolkit.Razor.Dynamic {
    using System;
    using System.Text;
    using System.Collections.Generic;
    using System.Linq;
    using System.IO;
    using YJC.Toolkit.Razor;
    using YJC.Toolkit.Web;
    using System.Data;
    using YJC.Toolkit.MetaData;
    using YJC.Toolkit.Data;
    using YJC.Toolkit.Sys;
    using YJC.Toolkit.Accounting;
    
    
    public class dworkspacemygitrepmituworkmituservertestmanagewebxmlrazortemplatebootcssaccounteditmaincshtml : YJC.Toolkit.Accounting.AccountEditTemplate {
        
#line hidden
 
    string GetJson(Tk5NormalTableData table)
    {
        var json = string.Format("{{\"Tables\":[{0}]}}", table.JsonFields);
        return StringUtil.EscapeHtmlAttribute(json);
    } 

        
        public dworkspacemygitrepmituworkmituservertestmanagewebxmlrazortemplatebootcssaccounteditmaincshtml() {
        }
        
        public override void Execute() {
  
    NormalEditData pageData = ViewBag.PageData;
    //HtmlAttribute attribute = pageData.DialogMode ? new HtmlAttribute("data-dialog-action", "close")
    //    : new HtmlAttribute("data-url", HtmlUtil.GetRetUrl((DataSet)Model));
    //HtmlAttribute retAttr = new HtmlAttribute("data-action", "return");

    DataRow dataRow = null; // HtmlUtil.GetMainRow((DataSet)Model, ViewBag);
    Tk5NormalTableData table = ViewBag.MetaData.Table;
    List<Tk5FieldInfoEx> hiddenFields = table.HiddenList;
    List<Tk5FieldInfoEx> normalFields = table.TableList;
    int columnCount = table.ColumnCount;
    int columnWidth = 12 / columnCount;
    int fieldsCount = normalFields.Count;
    int columnFieldCount = fieldsCount / columnCount;
    
     if ((fieldsCount % columnCount) != 0){
        ++columnFieldCount;
    }
     
    //bool showCaption = pageData.ShowCaption;
    //string dataClass = showCaption ? string.Empty : "class=\"nocaption\"";

WriteLiteral("\r\n");

DefineSection("DefaultButtons", () => {

WriteLiteral("\r\n    ");

WriteLiteral("\r\n");

});

  

WriteLiteral("\r\n<form");

WriteAttribute("action", Tuple.Create(" action=\"", 1753), Tuple.Create("\"", 1790)
, Tuple.Create(Tuple.Create("", 1762), Tuple.Create<System.Object, System.Int32>(ViewBag.PageData.FormAction
, 1762), false)
);

WriteLiteral(" method=\"POST\"");

WriteLiteral(" id=\"PostForm\"");

WriteLiteral(" class=\"tk-dataform p5 mb15\"");

WriteLiteral(" role=\"form\"");

WriteLiteral(" data-check=\"true\"");

WriteLiteral(" data-post=\"");

                                                                                                                                        Write(GetJson(table));

WriteLiteral("\"");

WriteLiteral(">\r\n    <div");

WriteAttribute("id", Tuple.Create(" id=\"", 1916), Tuple.Create("\"", 1937)
, Tuple.Create(Tuple.Create("", 1921), Tuple.Create<System.Object, System.Int32>(table.TableName
, 1921), false)
);

WriteAttribute("class", Tuple.Create(" class=\"", 1938), Tuple.Create("\"", 2033)
, Tuple.Create(Tuple.Create("", 1946), Tuple.Create<System.Object, System.Int32>(HtmlUtil.MergeClass("tk-datatable table-row", "column" + table.ColumnCount.ToString())
, 1946), false)
);

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"hide\"");

WriteLiteral(">\r\n            ");

WriteLiteral("\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n");

            
             for (int i = 0; i < columnCount; ++i)
            {
                
                  
                    int start = i * columnFieldCount;
                    int end = start + columnFieldCount;
                    if (end > fieldsCount){
                       end = fieldsCount;
                    }
                
                 

WriteLiteral("                <div");

WriteAttribute("class", Tuple.Create(" class=\"", 2605), Tuple.Create("\"", 2650)
, Tuple.Create(Tuple.Create("", 2613), Tuple.Create<System.Object, System.Int32>("col-sm-" + columnWidth.ToString()
, 2613), false)
);

WriteLiteral(">\r\n                    <table");

WriteLiteral(" class=\"table\"");

WriteLiteral(">\r\n                        <tr>\r\n                            <th>资产</th>\r\n       " +
"                     <th>行次</th>\r\n                            <th>期末数</th>\r\n    " +
"                    </tr>\r\n");

                        
                         for (int j = start; j < end; ++j)
                        {
                            
                              
                            var field = normalFields[j];

                            Tuple<int, byte, FieldStyle> info = field.Tag as Tuple<int, byte, FieldStyle>;
                            string intendClass = info.Item2 == 0 ? string.Empty : "class=\"pdl-" + info.Item2 + "\"";
                            
                             
                            
                             if (info.Item3 == FieldStyle.Title)
                            {

WriteLiteral("                                <tr");

WriteLiteral(" class=\"info\"");

WriteLiteral(">\r\n                                    <td>");

                                   Write(field.DisplayName);

WriteLiteral("</td>\r\n                                    <td></td>\r\n                           " +
"         <td></td>\r\n                                </tr>\r\n");

                            }
                            else
                            {

WriteLiteral("                            <tr>\r\n                                <td ");

                               Write(intendClass);

WriteLiteral(">");

                                            Write(field.DisplayName);

WriteLiteral("</td>\r\n                                <td>");

                               Write(info.Item1);

WriteLiteral("</td>\r\n                                <td>\r\n                                    " +
"<span");

WriteLiteral(" class=\"tk-control\"");

WriteLiteral(">");

                                                        Write(field.Control(dataRow, (DataSet)Model, true));

WriteLiteral("</span>\r\n                                </td>\r\n                            </tr>" +
"\r\n");

                            }
                             
                            
                                        
                        }

WriteLiteral("                    </table>\r\n                </div>\r\n");

            }

WriteLiteral("        </div>\r\n    </div>\r\n</form>\r\n");

Write(RenderSectionOrDefault("ModuleButtons", "DefaultButtons"));

WriteLiteral("\r\n");

        }
    }
}
