//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YJC.Toolkit.Razor.Dynamic {
    using System;
    using System.Text;
    using System.Collections.Generic;
    using System.Linq;
    using System.IO;
    using YJC.Toolkit.Razor;
    using YJC.Toolkit.Web;
    using System.Data;
    using YJC.Toolkit.Data;
    using YJC.Toolkit.MetaData;
    using YJC.Toolkit.Sys;
    
    
    public class dworkspacemygitrepmituworkmituservertestmanagewebxmlrazortemplatebootcsstreedetailtemplatecshtml : YJC.Toolkit.Razor.NormalTreeDetailTemplate {
        
#line hidden
        
        public dworkspacemygitrepmituworkmituservertestmanagewebxmlrazortemplatebootcsstreedetailtemplatecshtml() {
        }
        
        public override void Execute() {
  
    DataSet dataSet = Model;
    DataRow dataRow = HtmlUtil.GetMainRow(Model, ViewBag);

WriteLiteral("\r\n\r\n");

DefineSection("ModuleButtons", () => {

WriteLiteral("\r\n    <div");

WriteLiteral(" class=\"text-center clearfix mt5\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

   Write(BootcssUtil.CreateDetailButtons(dataSet, dataRow));

WriteLiteral("\r\n    </div>\r\n");

});

Write(RenderSectionIfDefined("Main", "../Detail/main.cshtml", Model));

        }
    }
}
