//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YJC.Toolkit.Razor.Dynamic {
    using System;
    using System.Text;
    using System.Collections.Generic;
    using System.Linq;
    using System.IO;
    using YJC.Toolkit.Razor;
    using YJC.Toolkit.Web;
    using YJC.Toolkit.Sys;
    using YJC.Toolkit.Data;
    using System.Data;
    
    
    public class dworkspacemygitrepmituworkmituservertestmanagewebxmlrazorusermanageruserpartcshtml : YJC.Toolkit.Razor.NormalCustomTemplate {
        
#line hidden
            
    string IsChecked(DataRow row, HashSet<int> partSet)
    {
        int id = row["Id"].Value<int>();
        if (partSet.Contains(id))
            return "checked";
        return string.Empty;
    }

        
        public dworkspacemygitrepmituworkmituservertestmanagewebxmlrazorusermanageruserpartcshtml() {
        }
        
        public override void Execute() {
  
    DataSet dataSet = (DataSet)Model;
    DataTable userTable = dataSet.Tables["UserPart"];
    HashSet<int> partSet = new HashSet<int>();
    if (userTable != null)
    {
        foreach (DataRow row in userTable.Rows)
            partSet.Add(row["PartId"].Value<int>());
    }
    DataTable partTable = dataSet.Tables["Part"];

WriteLiteral("\r\n");

DefineSection("Main", () => {

WriteLiteral("\r\n    <div");

WriteLiteral(" class=\"mt10\"");

WriteLiteral(">\r\n        <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" id=\"UserId\"");

WriteAttribute("value", Tuple.Create(" value=\"", 856), Tuple.Create("\"", 911)
, Tuple.Create(Tuple.Create("", 864), Tuple.Create<System.Object, System.Int32>(dataSet.GetFieldValue("QueryString", "UserId")
, 864), false)
);

WriteLiteral(" />\r\n    </div>\r\n");

    
     if (partTable != null)
    {

WriteLiteral("        <div");

WriteLiteral(" class=\"panel panel-default\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"panel-heading\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"pull-right\"");

WriteLiteral(">\r\n                    <a");

WriteLiteral(" class=\"mr5 checkall\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(">全选</a>\r\n                    <a");

WriteLiteral(" class=\"mr5 anticheck\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(">反选</a>\r\n                    <a");

WriteLiteral(" class=\"mr5 uncheckall\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(">全不选</a>\r\n                </div>\r\n                角色\r\n            </div>\r\n       " +
"     <div");

WriteLiteral(" class=\"panel-body\"");

WriteLiteral(">\r\n");

                
                 foreach (DataRow row in partTable.Rows)
                {

WriteLiteral("                    <div");

WriteLiteral(" class=\"w33p pull-left\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"checkbox\"");

WriteLiteral(">\r\n                            <label>\r\n                                <input");

WriteLiteral(" type=\"checkbox\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1646), Tuple.Create("\"", 1674)
, Tuple.Create(Tuple.Create("", 1654), Tuple.Create<System.Object, System.Int32>(row.GetString("Id")
, 1654), false)
);

WriteLiteral(" ");

                                                                               Write(IsChecked(row, partSet));

WriteLiteral(">");

                                                                                                        Write(row.GetString("Name"));

WriteLiteral("</label>\r\n                        </div>\r\n                    </div>\r\n");

                }

WriteLiteral("            </div>\r\n        </div>\r\n");

    }

WriteLiteral("    <div");

WriteLiteral(" class=\"text-center clearfix pt10 mb15\"");

WriteLiteral(">\r\n");

        
         if (partTable != null)
        {
            
       Write(BootcssUtil.Button("保存", "btn-save mr10", BootcssButton.Primary, false));

                                                                                    
        }

WriteLiteral("        ");

   Write(BootcssUtil.Button("关闭", "", BootcssButton.Default, false, new HtmlAttribute("data-dialog-action", "close")));

WriteLiteral("\r\n    </div>\r\n");

});

        }
    }
}
