//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YJC.Toolkit.Razor.Dynamic {
    using System;
    using System.Text;
    using System.Collections.Generic;
    using System.Linq;
    using System.IO;
    using YJC.Toolkit.Razor;
    using YJC.Toolkit.Web;
    using System.Data;
    using YJC.Toolkit.MetaData;
    using YJC.Toolkit.Data;
    using YJC.Toolkit.Sys;
    using YJC.Toolkit.Accounting;
    
    
    public class dworkspacemygitrepmituworkweixinframeworkworkaccountmanagewebxmlrazortemplatebootcssaccounteditmaincshtml : YJC.Toolkit.Accounting.AccountEditTemplate {
        
#line hidden
 
    string GetJson(Tk5NormalTableData table)
    {
        var normalJson = "{\"Table\":\"Info\",\"SearchMethod\":\"Id\",\"JsonType\":\"Object\",\"Fields\":[{\"Name\":\"ReportId\",\"Type\":\"Hidden\"},{\"Name\":\"Company\",\"Type\":\"Hidden\"},{\"Name\":\"ReportYear\",\"Type\":\"Combo\"},{\"Name\":\"ReportMonth\",\"Type\":\"Combo\"},{\"Name\":\"ReportType\",\"Type\":\"Combo\"},{\"Name\":\"ReportName\",\"Type\":\"Hidden\"}]}";
        var json = string.Format("{{\"Tables\":[{0}, {1}]}}", table.JsonFields, normalJson);
        return StringUtil.EscapeHtmlAttribute(json);
    } 

        
        public dworkspacemygitrepmituworkweixinframeworkworkaccountmanagewebxmlrazortemplatebootcssaccounteditmaincshtml() {
        }
        
        public override void Execute() {
  
    NormalEditData pageData = ViewBag.PageData;
    HtmlAttribute retAttr = new HtmlAttribute("data-action", "return");
    HtmlAttribute subAttr = new HtmlAttribute("data-validType", "allClear");

    Tk5NormalTableData table = ViewBag.MetaData.Table;
    List<Tk5FieldInfoEx> hiddenFields = table.HiddenList;
    List<Tk5FieldInfoEx> normalFields = table.TableList;
    int columnCount = table.ColumnCount;
    int columnWidth = 12 / columnCount;
    int fieldsCount = normalFields.Count;
    int columnFieldCount = fieldsCount / columnCount;
    
     if ((fieldsCount % columnCount) != 0){
        ++columnFieldCount;
    }
     

    ReportObjectData model = Model as ReportObjectData;
    ObjectContainer mainObject = model.Object;// HtmlUtil.GetMainObject(Model, ViewBag);
    ReportInfo rptInfo = model.Info;
    HtmlAttribute attribute = new HtmlAttribute("data-url", ("Library/WebListXmlPage.tkx?Source=Accounting/ReportData&Company=" + rptInfo.Company).AppVirutalPath());
    int startYear = DateTime.Today.Year;

WriteLiteral("\r\n");

DefineSection("DefaultButtons", () => {

WriteLiteral("\r\n    <div");

WriteLiteral(" class=\"text-center clearfix\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

   Write(BootcssUtil.Button(pageData.SaveButtonCaption, "btn-submit", BootcssButton.Primary, false, subAttr));

WriteLiteral("\r\n");

WriteLiteral("        ");

   Write(BootcssUtil.Button(pageData.CancelCaption, "m10", BootcssButton.Default, false, retAttr, attribute));

WriteLiteral("\r\n    </div>\r\n");

});

  

WriteLiteral("\r\n<form");

WriteAttribute("action", Tuple.Create(" action=\"", 2239), Tuple.Create("\"", 2276)
, Tuple.Create(Tuple.Create("", 2248), Tuple.Create<System.Object, System.Int32>(ViewBag.PageData.FormAction
, 2248), false)
);

WriteLiteral(" method=\"POST\"");

WriteLiteral(" data-toggle=\"validator\"");

WriteLiteral(" id=\"PostForm\"");

WriteLiteral(" class=\"tk-dataform p5 mb15\"");

WriteLiteral(" role=\"form\"");

WriteLiteral(" data-check=\"true\"");

WriteLiteral(" data-post=\"");

                                                                                                                                                                Write(GetJson(table));

WriteLiteral("\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"row tk-datatable table-row\"");

WriteLiteral(" id=\"Info\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-sm-4\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" class=\"col-sm-4 ver-middle\"");

WriteLiteral(">报表类型：</label>\r\n                <div");

WriteLiteral(" class=\"col-sm-8 \"");

WriteLiteral(">\r\n                    <span");

WriteLiteral(" class=\"tk-control\"");

WriteLiteral(">\r\n                        <select");

WriteLiteral(" id=\"ReportType\"");

WriteLiteral(" name=\"ReportType\"");

WriteLiteral(" class=\"cc-select\"");

WriteLiteral(" data-title=\"市场板块\"");

WriteLiteral(">\r\n                            <option");

WriteLiteral(" value=\"01\"");

WriteLiteral(" ");

                                                if (rptInfo.ReportType == "01") {
WriteLiteral("  ");

WriteLiteral(" selected\r\n");

                                                                                                             }
WriteLiteral(">\r\n                                合并报表\r\n                            </option>\r\n " +
"                           <option");

WriteLiteral(" value=\"02\"");

WriteLiteral(" ");

                                                if (rptInfo.ReportType == "02") {
WriteLiteral("  ");

WriteLiteral(" selected\r\n");

                                                                                                             }
WriteLiteral(">\r\n                                母公司报表\r\n                            </option>\r\n" +
"                        </select>\r\n                    </span>\r\n                " +
"</div>\r\n                <br />\r\n            </div>\r\n        </div>\r\n        <div" +
"");

WriteLiteral(" class=\"col-sm-6\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" class=\"col-sm-2 ver-middle\"");

WriteLiteral(">日期：</label>\r\n                <span");

WriteLiteral(" class=\"tk-control\"");

WriteLiteral(">\r\n                    <select");

WriteLiteral(" id=\"ReportYear\"");

WriteLiteral(" name=\"ReportYear\"");

WriteLiteral(" class=\"cc-select\"");

WriteLiteral(">\r\n");

                        
                         for (int i = 0; i < 20; ++i)
                        {
                            
                              
                            int year = startYear - i;
                            string selected = year == rptInfo.ReportYear ? "selected" : string.Empty;
                            
                             

WriteLiteral("                            <option");

WriteAttribute("value", Tuple.Create(" value=\"", 4106), Tuple.Create("\"", 4119)
, Tuple.Create(Tuple.Create("", 4114), Tuple.Create<System.Object, System.Int32>(year
, 4114), false)
);

WriteLiteral(" ");

                                             Write(selected);

WriteLiteral(">");

                                                       Write(year);

WriteLiteral("</option>\r\n");

                        }

WriteLiteral("                    </select>\r\n                    <label");

WriteLiteral(" class=\"mr5 ver-middle\"");

WriteLiteral(">年</label>\r\n                    <select");

WriteLiteral(" id=\"ReportMonth\"");

WriteLiteral(" name=\"ReportMonth\"");

WriteLiteral(" class=\"cc-select\"");

WriteLiteral(">\r\n");

                        
                         for (int i = 0; i < 4; ++i)
                        {
                            
                              
                            int month = (i + 1) * 3;
                            string selected = month == rptInfo.ReportMonth ? "selected" : string.Empty;
                            
                             

WriteLiteral("                            <option");

WriteAttribute("value", Tuple.Create(" value=\"", 4688), Tuple.Create("\"", 4702)
, Tuple.Create(Tuple.Create("", 4696), Tuple.Create<System.Object, System.Int32>(month
, 4696), false)
);

WriteLiteral(" ");

                                              Write(selected);

WriteLiteral(">");

                                                        Write(month);

WriteLiteral("</option>\r\n");

                        }

WriteLiteral("                    </select>\r\n\r\n                    <label");

WriteLiteral(" class=\"mr5 ver-middle\"");

WriteLiteral(">月</label>\r\n                </span>\r\n            </div>\r\n            <br />\r\n    " +
"    </div>\r\n        <div");

WriteLiteral(" class=\"col-sm-2\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"row ml20\"");

WriteLiteral(">\r\n                <strong");

WriteLiteral(" class=\"ver-middle\"");

WriteLiteral(">单位：元</strong>\r\n                <input");

WriteLiteral(" id=\"ReportName\"");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("value", Tuple.Create(" value=\"", 5111), Tuple.Create("\"", 5138)
, Tuple.Create(Tuple.Create("", 5119), Tuple.Create<System.Object, System.Int32>(rptInfo.ReportName
, 5119), false)
);

WriteLiteral(">\r\n                <input");

WriteLiteral(" id=\"Company\"");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("value", Tuple.Create(" value=\"", 5191), Tuple.Create("\"", 5215)
, Tuple.Create(Tuple.Create("", 5199), Tuple.Create<System.Object, System.Int32>(rptInfo.Company
, 5199), false)
);

WriteLiteral(">\r\n                <input");

WriteLiteral(" id=\"ReportId\"");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("value", Tuple.Create(" value=\"", 5269), Tuple.Create("\"", 5294)
, Tuple.Create(Tuple.Create("", 5277), Tuple.Create<System.Object, System.Int32>(rptInfo.ReportId
, 5277), false)
);

WriteLiteral(">\r\n            </div>\r\n        </div>\r\n    </div>\r\n    <br />\r\n    <div");

WriteAttribute("id", Tuple.Create(" id=\"", 5366), Tuple.Create("\"", 5387)
, Tuple.Create(Tuple.Create("", 5371), Tuple.Create<System.Object, System.Int32>(table.TableName
, 5371), false)
);

WriteAttribute("class", Tuple.Create(" class=\"", 5388), Tuple.Create("\"", 5483)
, Tuple.Create(Tuple.Create("", 5396), Tuple.Create<System.Object, System.Int32>(HtmlUtil.MergeClass("tk-datatable table-row", "column" + table.ColumnCount.ToString())
, 5396), false)
);

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"hide\"");

WriteLiteral(">\r\n            ");

WriteLiteral("\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n");

            
             for (int i = 0; i < columnCount; ++i)
            {
                
                  
                int start = i * columnFieldCount;
                int end = start + columnFieldCount;
                if (end > fieldsCount)
                {
                    end = fieldsCount;
                }
                
                 

WriteLiteral("                <div");

WriteAttribute("class", Tuple.Create(" class=\"", 6066), Tuple.Create("\"", 6111)
, Tuple.Create(Tuple.Create("", 6074), Tuple.Create<System.Object, System.Int32>("col-sm-" + columnWidth.ToString()
, 6074), false)
);

WriteLiteral(">\r\n                    <table");

WriteLiteral(" class=\"table\"");

WriteLiteral(">\r\n                        <tr>\r\n                            <th>资产</th>\r\n       " +
"                     <th>行次</th>\r\n                            <th>期末数</th>\r\n    " +
"                    </tr>\r\n");

                        
                         for (int j = start; j < end; ++j)
                        {
                            
                              
                            var field = normalFields[j];

                            Tuple<int, byte, FieldStyle> info = field.Tag as Tuple<int, byte, FieldStyle>;
                            string intendClass = info.Item2 == 0 ? string.Empty : "class=\"pdl-" + info.Item2 + "\"";
                            
                             
                            
                             if (info.Item3 == FieldStyle.Title)
                            {

WriteLiteral("                                <tr");

WriteLiteral(" class=\"info\"");

WriteLiteral(">\r\n                                    <td>");

                                   Write(field.DisplayName);

WriteLiteral("</td>\r\n                                    <td></td>\r\n                           " +
"         <td></td>\r\n                                </tr>\r\n");

                            }
                            else
                            {

WriteLiteral("                                <tr>\r\n                                    <td ");

                                   Write(intendClass);

WriteLiteral(">");

                                                Write(field.DisplayName);

WriteLiteral("</td>\r\n                                    <td>");

                                   Write(info.Item1);

WriteLiteral("</td>\r\n                                    <td>\r\n                                " +
"        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                            <span");

WriteLiteral(" class=\"tk-control\"");

WriteLiteral(">");

                                                                Write(field.InputByLocalName(mainObject, true));

WriteLiteral("</span>\r\n                                        </div>\r\n                        " +
"            </td>\r\n                                </tr>\r\n");

                            }
                             
                        }

WriteLiteral("                    </table>\r\n                </div>\r\n");

            }

WriteLiteral("        </div>\r\n    </div>\r\n");

WriteLiteral("    ");

Write(RenderSectionOrDefault("ModuleButtons", "DefaultButtons"));

WriteLiteral("\r\n</form>\r\n\r\n");

        }
    }
}
