//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YJC.Toolkit.Razor.Dynamic {
    using System;
    using System.Text;
    using System.Collections.Generic;
    using System.Linq;
    using System.IO;
    using YJC.Toolkit.Razor;
    using YJC.Toolkit.Web;
    using System.Data;
    using YJC.Toolkit.Sys;
    
    
    public class dworkspacemygitrepmituworkweixinframeworkworkaccountmanagewebxmlrazoraccountingreportlistcshtml : YJC.Toolkit.Razor.NormalListTemplate {
        
#line hidden
        
        public dworkspacemygitrepmituworkweixinframeworkworkaccountmanagewebxmlrazoraccountingreportlistcshtml() {
        }
        
        public override void Execute() {
  
    DataSet dataSet = (DataSet)Model;
    string companyName = dataSet.GetFieldValue("CompanyName", "COM_FULL_NAME").ToString();
    string title = ViewBag.Title;
    if (!string.IsNullOrEmpty(companyName)) {
        title = companyName + "的" + title;
    }

WriteLiteral("\r\n");

DefineSection("Header", () => {

WriteLiteral("\r\n    <h1>");

   Write(title);

WriteLiteral("</h1>\r\n");

});

        }
    }
}
