//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YJC.Toolkit.Razor.Dynamic {
    using System;
    using System.Text;
    using System.Collections.Generic;
    using System.Linq;
    using System.IO;
    using YJC.Toolkit.Razor;
    using YJC.Toolkit.Web;
    using YJC.Toolkit.Sys;
    
    
    public class dcinternalfilemitucorpweixinwebxmlrazorcxcsedittitlecshtml : YJC.Toolkit.Razor.ToolkitTemplate {
        
#line hidden
        
        public dcinternalfilemitucorpweixinwebxmlrazorcxcsedittitlecshtml() {
        }
        
        public override void Execute() {
WriteLiteral("<div");

WriteLiteral(" class=\"\"");

WriteLiteral(" style=\"background-color: #428bca; color: #fff; margin-left: -20px; margin-right:" +
" -20px\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"dropdown pull-right\"");

WriteLiteral(">\r\n        <button");

WriteLiteral(" class=\"btn btn-default dropdown-toggle mr20\"");

WriteLiteral(" style=\"margin-top: 3px\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" id=\"dropdownMenu1\"");

WriteLiteral(" data-toggle=\"dropdown\"");

WriteLiteral(">\r\n            导航<i");

WriteLiteral(" class=\"icon-reorder\"");

WriteLiteral("></i>\r\n        </button>\r\n        <ul");

WriteLiteral(" class=\"dropdown-menu\"");

WriteLiteral(" role=\"menu\"");

WriteLiteral(" aria-labelledby=\"dropdownMenu1\"");

WriteLiteral(">\r\n            <li");

WriteLiteral(" role=\"presentation\"");

WriteLiteral("><a");

WriteLiteral(" role=\"menuitem\"");

WriteLiteral(" tabindex=\"-1\"");

WriteAttribute("href", Tuple.Create(" href=\"", 522), Tuple.Create("\"", 596)
, Tuple.Create(Tuple.Create("", 529), Tuple.Create<System.Object, System.Int32>("Library/WebListXmlPage.tkx?Source=Cxcs/ZuiXin".AppVirutalPath()
, 529), false)
);

WriteLiteral(">最新发布</a></li>\r\n            <li");

WriteLiteral(" role=\"presentation\"");

WriteLiteral("><a");

WriteLiteral(" role=\"menuitem\"");

WriteLiteral(" tabindex=\"-1\"");

WriteAttribute("href", Tuple.Create(" href=\"", 681), Tuple.Create("\"", 756)
, Tuple.Create(Tuple.Create("", 688), Tuple.Create<System.Object, System.Int32>("Library/WebListXmlPage.tkx?Source=Cxcs/TongZhi".AppVirutalPath()
, 688), false)
);

WriteLiteral(">通知公告</a></li>\r\n            <li");

WriteLiteral(" role=\"presentation\"");

WriteLiteral("><a");

WriteLiteral(" role=\"menuitem\"");

WriteLiteral(" tabindex=\"-1\"");

WriteAttribute("href", Tuple.Create(" href=\"", 841), Tuple.Create("\"", 919)
, Tuple.Create(Tuple.Create("", 848), Tuple.Create<System.Object, System.Int32>("Library/WebListXmlPage.tkx?Source=Cxcs/FaGuiIndex".AppVirutalPath()
, 848), false)
);

WriteLiteral(">政策法规</a></li>\r\n            <li");

WriteLiteral(" role=\"presentation\"");

WriteLiteral("><a");

WriteLiteral(" role=\"menuitem\"");

WriteLiteral(" tabindex=\"-1\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1004), Tuple.Create("\"", 1079)
, Tuple.Create(Tuple.Create("", 1011), Tuple.Create<System.Object, System.Int32>("Library/WebListXmlPage.tkx?Source=Cxcs/BanShui".AppVirutalPath()
, 1011), false)
);

WriteLiteral(">办税流程</a></li>\r\n            <li");

WriteLiteral(" role=\"presentation\"");

WriteLiteral("><a");

WriteLiteral(" role=\"menuitem\"");

WriteLiteral(" tabindex=\"-1\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1164), Tuple.Create("\"", 1238)
, Tuple.Create(Tuple.Create("", 1171), Tuple.Create<System.Object, System.Int32>("Library/WebListXmlPage.tkx?Source=Cxcs/NaShui".AppVirutalPath()
, 1171), false)
);

WriteLiteral(">纳税辅导</a></li>\r\n            <li");

WriteLiteral(" role=\"presentation\"");

WriteLiteral(" class=\"divider\"");

WriteLiteral("></li>\r\n            <li");

WriteLiteral(" role=\"presentation\"");

WriteLiteral("><a");

WriteLiteral(" role=\"menuitem\"");

WriteLiteral(" tabindex=\"-1\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1382), Tuple.Create("\"", 1459)
, Tuple.Create(Tuple.Create("", 1389), Tuple.Create<System.Object, System.Int32>("Library/WebInsertXmlPage.tkx?Source=CXCS/Consult".AppVirutalPath()
, 1389), false)
);

WriteLiteral(">业务咨询</a></li>\r\n            <li");

WriteLiteral(" role=\"presentation\"");

WriteLiteral("><a");

WriteLiteral(" role=\"menuitem\"");

WriteLiteral(" tabindex=\"-1\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1544), Tuple.Create("\"", 1624)
, Tuple.Create(Tuple.Create("", 1551), Tuple.Create<System.Object, System.Int32>("Library/WebInsertXmlPage.tkx?Source=CXCS/Suggestion".AppVirutalPath()
, 1551), false)
);

WriteLiteral(">意见与投诉</a></li>\r\n            <li");

WriteLiteral(" role=\"presentation\"");

WriteLiteral("><a");

WriteLiteral(" role=\"menuitem\"");

WriteLiteral(" tabindex=\"-1\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1710), Tuple.Create("\"", 1784)
, Tuple.Create(Tuple.Create("", 1717), Tuple.Create<System.Object, System.Int32>("Library/WebListXmlPage.tkx?Source=CXCS/GeShui".AppVirutalPath()
, 1717), false)
);

WriteLiteral(">个税计算器</a></li>\r\n            <li");

WriteLiteral(" role=\"presentation\"");

WriteLiteral(" class=\"divider\"");

WriteLiteral("></li>\r\n            <li");

WriteLiteral(" role=\"presentation\"");

WriteLiteral("><a");

WriteLiteral(" role=\"menuitem\"");

WriteLiteral(" tabindex=\"-1\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1929), Tuple.Create("\"", 2003)
, Tuple.Create(Tuple.Create("", 1936), Tuple.Create<System.Object, System.Int32>("Library/WebListXmlPage.tkx?Source=CXCS/Lianxi".AppVirutalPath()
, 1936), false)
);

WriteLiteral(">联系我们</a></li>\r\n        </ul>\r\n    </div>\r\n    <h4");

WriteLiteral(" class=\"vam dib ml20\"");

WriteLiteral(">杭州湾新区地税局</h4>\r\n</div>\r\n");

        }
    }
}
