//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YJC.Toolkit.Razor.Dynamic {
    using System;
    using System.Text;
    using System.Collections.Generic;
    using System.Linq;
    using System.IO;
    using YJC.Toolkit.Razor;
    using YJC.Toolkit.Web;
    using YJC.Toolkit.Sys;
    
    
    public class dcinternalfilemitucorpweixinwebxmlrazorcxcsfaguiindexcshtml : YJC.Toolkit.Razor.ToolkitTemplate {
        
#line hidden
        
        public dcinternalfilemitucorpweixinwebxmlrazorcxcsfaguiindexcshtml() {
        }
        
        public override void Execute() {
WriteLiteral("<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    <title>政策法规</title>\r\n    <meta");

WriteLiteral(" http-equiv=\"X-UA-Compatible\"");

WriteLiteral(" content=\"IE=edge\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" http-equiv=\"Content-Type\"");

WriteLiteral(" content=\"text/html; charset=utf-8\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable" +
"=0;\"");

WriteLiteral(" />\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteAttribute("href", Tuple.Create(" href=\"", 446), Tuple.Create("\"", 519)
, Tuple.Create(Tuple.Create("", 453), Tuple.Create<System.Object, System.Int32>("toolkitjs/v5/bootstrap/css/bootstrap.min.css".AppVirutalPath()
, 453), false)
);

WriteLiteral(" />\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteAttribute("href", Tuple.Create(" href=\"", 567), Tuple.Create("\"", 646)
, Tuple.Create(Tuple.Create("", 574), Tuple.Create<System.Object, System.Int32>("toolkitjs/v5/bootstrap/css/bootstrap-theme.min.css".AppVirutalPath()
, 574), false)
);

WriteLiteral(" />\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteAttribute("href", Tuple.Create(" href=\"", 694), Tuple.Create("\"", 770)
, Tuple.Create(Tuple.Create("", 701), Tuple.Create<System.Object, System.Int32>("toolkitjs/v5/bootstrap/css/font-awesome.min.css".AppVirutalPath()
, 701), false)
);

WriteLiteral(" />\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteAttribute("href", Tuple.Create(" href=\"", 818), Tuple.Create("\"", 882)
, Tuple.Create(Tuple.Create("", 825), Tuple.Create<System.Object, System.Int32>("toolkitcss/v5/commonM/style.css?v=1".AppVirutalPath()
, 825), false)
);

WriteLiteral(" />\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteAttribute("href", Tuple.Create(" href=\"", 930), Tuple.Create("\"", 978)
, Tuple.Create(Tuple.Create("", 937), Tuple.Create<System.Object, System.Int32>("usercss/docList.css".AppVirutalPath()
, 937), false)
);

WriteLiteral(" />\r\n    <style>\r\n        a:hover\r\n        {\r\n            text-decoration: none;\r" +
"\n        }\r\n    </style>\r\n</head>\r\n<body");

WriteLiteral(" id=\"WebListXmlPage\"");

WriteLiteral(" data-webpath=\"");

                                   Write(HtmlUtil.AppVirtualPath);

WriteLiteral("\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" id=\"metaData\"");

WriteLiteral(" class=\"Hide\"");

WriteLiteral(" data-toolbar=\"false\"");

WriteLiteral(" data-option=\"false\"");

WriteLiteral("></div>\r\n");

WriteLiteral("        ");

   Write(RenderLocalPartial("EditTitle.cshtml", null));

WriteLiteral("\r\n        <form");

WriteLiteral(" class=\"navbar-form\"");

WriteLiteral(" role=\"search\"");

WriteLiteral(" id=\"QueryForm\"");

WriteLiteral(" data-post=\"{&quot;Table&quot;:&quot;CS_DOCUMENT&quot;,&quot;SearchMethod&quot;:&" +
"quot;Id&quot;,&quot;JsonType&quot;:&quot;Object&quot;,&quot;Fields&quot;:[{&quot" +
";Name&quot;:&quot;Title&quot;,&quot;Type&quot;:&quot;Text&quot;}]}\"");

WriteLiteral(" data-resolver=\"TaxDocument\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" id=\"CS_DOCUMENT\"");

WriteLiteral(" class=\"table-row\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"input-group w100p\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" placeholder=\"关键字\"");

WriteLiteral(" id=\"Title\"");

WriteLiteral(" value=\"\"");

WriteLiteral(" />\r\n                    <div");

WriteLiteral(" class=\"input-group-btn\"");

WriteLiteral(">\r\n                        <button");

WriteLiteral(" class=\"btn btn-default btn-search\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(">\r\n                            <span");

WriteLiteral(" class=\"glyphicon glyphicon-search\"");

WriteLiteral(" />\r\n                        </button>\r\n                    </div>\r\n             " +
"   </div>\r\n            </div>\r\n        </form>\r\n        <div");

WriteLiteral(" class=\"tk-datalist\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" id=\"listData\"");

WriteLiteral(">\r\n                <ul");

WriteLiteral(" id=\"pageList\"");

WriteLiteral(" class=\"list-group\"");

WriteLiteral(" data-url=\"");

                                                           Write("Library/WebListXmlPage.tkx?Source=Cxcs/FaGui".AppVirutalPath());

WriteLiteral("\"");

WriteLiteral(">\r\n                    <li");

WriteLiteral(" class=\"list-group-item\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" href=\"javascript:void(0);\"");

WriteLiteral(" data-url=\"");

                                                            Write("Library/WebListXmlPage.tkx?Source=Cxcs/FaGui".AppVirutalPath());

WriteLiteral("\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"col-xs-11 col-sm-11 col-md-11 col-lg-11 lv-vam\"");

WriteLiteral(">全部法规文件</div>\r\n                                <div");

WriteLiteral(" class=\"col-xs-1 col-sm-1 col-md-1 col-lg-1 lv-vam pv1\"");

WriteLiteral("><i");

WriteLiteral(" class=\"icon-angle-right icon-large\"");

WriteLiteral("></i></div>\r\n                            </div>\r\n                        </a>\r\n  " +
"                  </li>\r\n                    <li");

WriteLiteral(" class=\"list-group-item\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" target=\"_blank\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"condition\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"col-xs-11 col-sm-11 col-md-11 col-lg-11 lv-vam\"");

WriteLiteral(">税收征管</div>\r\n                                <div");

WriteLiteral(" class=\"col-xs-1 col-sm-1 col-md-1 col-lg-1 lv-vam pv1\"");

WriteLiteral("><i");

WriteLiteral(" class=\"icon-angle-right icon-large\"");

WriteLiteral("></i></div>\r\n                            </div>\r\n                        </a>\r\n  " +
"                  </li>\r\n                    <li");

WriteLiteral(" class=\"list-group-item\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" target=\"_blank\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"condition\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"col-xs-11 col-sm-11 col-md-11 col-lg-11 lv-vam\"");

WriteLiteral(">营业税</div>\r\n                                <div");

WriteLiteral(" class=\"col-xs-1 col-sm-1 col-md-1 col-lg-1 lv-vam pv1\"");

WriteLiteral("><i");

WriteLiteral(" class=\"icon-angle-right icon-large\"");

WriteLiteral("></i></div>\r\n                            </div>\r\n                        </a>\r\n  " +
"                  </li>\r\n                    <li");

WriteLiteral(" class=\"list-group-item\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" target=\"_blank\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"condition\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"col-xs-11 col-sm-11 col-md-11 col-lg-11 lv-vam\"");

WriteLiteral(">企业所得税</div>\r\n                                <div");

WriteLiteral(" class=\"col-xs-1 col-sm-1 col-md-1 col-lg-1 lv-vam pv1\"");

WriteLiteral("><i");

WriteLiteral(" class=\"icon-angle-right icon-large\"");

WriteLiteral("></i></div>\r\n                            </div>\r\n                        </a>\r\n  " +
"                  </li>\r\n                    <li");

WriteLiteral(" class=\"list-group-item\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" target=\"_blank\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"condition\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"col-xs-11 col-sm-11 col-md-11 col-lg-11 lv-vam\"");

WriteLiteral(">个人所得税</div>\r\n                                <div");

WriteLiteral(" class=\"col-xs-1 col-sm-1 col-md-1 col-lg-1 lv-vam pv1\"");

WriteLiteral("><i");

WriteLiteral(" class=\"icon-angle-right icon-large\"");

WriteLiteral("></i></div>\r\n                            </div>\r\n                        </a>\r\n  " +
"                  </li>\r\n                    <li");

WriteLiteral(" class=\"list-group-item\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" target=\"_blank\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"condition\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"col-xs-11 col-sm-11 col-md-11 col-lg-11 lv-vam\"");

WriteLiteral(">资源税</div>\r\n                                <div");

WriteLiteral(" class=\"col-xs-1 col-sm-1 col-md-1 col-lg-1 lv-vam pv1\"");

WriteLiteral("><i");

WriteLiteral(" class=\"icon-angle-right icon-large\"");

WriteLiteral("></i></div>\r\n                            </div>\r\n                        </a>\r\n  " +
"                  </li>\r\n                    <li");

WriteLiteral(" class=\"list-group-item\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" target=\"_blank\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"condition\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"col-xs-11 col-sm-11 col-md-11 col-lg-11 lv-vam\"");

WriteLiteral(">房产税</div>\r\n                                <div");

WriteLiteral(" class=\"col-xs-1 col-sm-1 col-md-1 col-lg-1 lv-vam pv1\"");

WriteLiteral("><i");

WriteLiteral(" class=\"icon-angle-right icon-large\"");

WriteLiteral("></i></div>\r\n                            </div>\r\n                        </a>\r\n  " +
"                  </li>\r\n                    <li");

WriteLiteral(" class=\"list-group-item\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" target=\"_blank\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"condition\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"col-xs-11 col-sm-11 col-md-11 col-lg-11 lv-vam\"");

WriteLiteral(">印花税</div>\r\n                                <div");

WriteLiteral(" class=\"col-xs-1 col-sm-1 col-md-1 col-lg-1 lv-vam pv1\"");

WriteLiteral("><i");

WriteLiteral(" class=\"icon-angle-right icon-large\"");

WriteLiteral("></i></div>\r\n                            </div>\r\n                        </a>\r\n  " +
"                  </li>\r\n                    <li");

WriteLiteral(" class=\"list-group-item\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" target=\"_blank\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"condition\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"col-xs-11 col-sm-11 col-md-11 col-lg-11 lv-vam\"");

WriteLiteral(">土地增值税</div>\r\n                                <div");

WriteLiteral(" class=\"col-xs-1 col-sm-1 col-md-1 col-lg-1 lv-vam pv1\"");

WriteLiteral("><i");

WriteLiteral(" class=\"icon-angle-right icon-large\"");

WriteLiteral("></i></div>\r\n                            </div>\r\n                        </a>\r\n  " +
"                  </li>\r\n                    <li");

WriteLiteral(" class=\"list-group-item\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" target=\"_blank\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"condition\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"col-xs-11 col-sm-11 col-md-11 col-lg-11 lv-vam\"");

WriteLiteral(">城市维护建设税</div>\r\n                                <div");

WriteLiteral(" class=\"col-xs-1 col-sm-1 col-md-1 col-lg-1 lv-vam pv1\"");

WriteLiteral("><i");

WriteLiteral(" class=\"icon-angle-right icon-large\"");

WriteLiteral("></i></div>\r\n                            </div>\r\n                        </a>\r\n  " +
"                  </li>\r\n                    <li");

WriteLiteral(" class=\"list-group-item\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" target=\"_blank\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"condition\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"col-xs-11 col-sm-11 col-md-11 col-lg-11 lv-vam\"");

WriteLiteral(">契税</div>\r\n                                <div");

WriteLiteral(" class=\"col-xs-1 col-sm-1 col-md-1 col-lg-1 lv-vam pv1\"");

WriteLiteral("><i");

WriteLiteral(" class=\"icon-angle-right icon-large\"");

WriteLiteral("></i></div>\r\n                            </div>\r\n                        </a>\r\n  " +
"                  </li>\r\n                    <li");

WriteLiteral(" class=\"list-group-item\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" target=\"_blank\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"condition\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"col-xs-11 col-sm-11 col-md-11 col-lg-11 lv-vam\"");

WriteLiteral(">车船税</div>\r\n                                <div");

WriteLiteral(" class=\"col-xs-1 col-sm-1 col-md-1 col-lg-1 lv-vam pv1\"");

WriteLiteral("><i");

WriteLiteral(" class=\"icon-angle-right icon-large\"");

WriteLiteral("></i></div>\r\n                            </div>\r\n                        </a>\r\n  " +
"                  </li>\r\n                    <li");

WriteLiteral(" class=\"list-group-item\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" target=\"_blank\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"condition\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"col-xs-11 col-sm-11 col-md-11 col-lg-11 lv-vam\"");

WriteLiteral(">城镇土地使用税</div>\r\n                                <div");

WriteLiteral(" class=\"col-xs-1 col-sm-1 col-md-1 col-lg-1 lv-vam pv1\"");

WriteLiteral("><i");

WriteLiteral(" class=\"icon-angle-right icon-large\"");

WriteLiteral("></i></div>\r\n                            </div>\r\n                        </a>\r\n  " +
"                  </li>\r\n                    <li");

WriteLiteral(" class=\"list-group-item\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" target=\"_blank\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"condition\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"col-xs-11 col-sm-11 col-md-11 col-lg-11 lv-vam\"");

WriteLiteral(">代征规费</div>\r\n                                <div");

WriteLiteral(" class=\"col-xs-1 col-sm-1 col-md-1 col-lg-1 lv-vam pv1\"");

WriteLiteral("><i");

WriteLiteral(" class=\"icon-angle-right icon-large\"");

WriteLiteral("></i></div>\r\n                            </div>\r\n                        </a>\r\n  " +
"                  </li>\r\n                </ul>\r\n            </div>\r\n        </di" +
"v>\r\n    </div>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 9691), Tuple.Create("\"", 9755)
, Tuple.Create(Tuple.Create("", 9697), Tuple.Create<System.Object, System.Int32>("toolkitjs/v5/lib/jquery-1.7.2.min.js".AppVirutalPath()
, 9697), false)
);

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 9802), Tuple.Create("\"", 9872)
, Tuple.Create(Tuple.Create("", 9808), Tuple.Create<System.Object, System.Int32>("toolkitjs/v5/bootstrap/js/bootstrap.min.js".AppVirutalPath()
, 9808), false)
);

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 9919), Tuple.Create("\"", 9978)
, Tuple.Create(Tuple.Create("", 9925), Tuple.Create<System.Object, System.Int32>("toolkitjs/v5/toolkit/toolkit.js".AppVirutalPath()
, 9925), false)
);

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 10025), Tuple.Create("\"", 10095)
, Tuple.Create(Tuple.Create("", 10031), Tuple.Create<System.Object, System.Int32>("toolkitjs/v5/toolkit/coreT/toolkit.page.js".AppVirutalPath()
, 10031), false)
);

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 10142), Tuple.Create("\"", 10216)
, Tuple.Create(Tuple.Create("", 10148), Tuple.Create<System.Object, System.Int32>("toolkitjs/v5/toolkit/coreT/toolkit.data.js?v=7".AppVirutalPath()
, 10148), false)
);

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 10263), Tuple.Create("\"", 10339)
, Tuple.Create(Tuple.Create("", 10269), Tuple.Create<System.Object, System.Int32>("toolkitjs/v5/toolkit/coreT/toolkit.weixin.js?v=5".AppVirutalPath()
, 10269), false)
);

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 10386), Tuple.Create("\"", 10454)
, Tuple.Create(Tuple.Create("", 10392), Tuple.Create<System.Object, System.Int32>("toolkitjs/v5/toolkit/coreT/toolkit.ui.js".AppVirutalPath()
, 10392), false)
);

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 10501), Tuple.Create("\"", 10571)
, Tuple.Create(Tuple.Create("", 10507), Tuple.Create<System.Object, System.Int32>("toolkitjs/v5/toolkit/coreT/toolkit.list.js".AppVirutalPath()
, 10507), false)
);

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
        $(document).ready(function () {
            $(""a.condition"").click(function () {
                var obj = $(this);
                var title = obj.text().trim();
                document.location.href = ""../Library/WebModuleRedirectPage.tkx?Source=SearchFaGui&useSource=true&Title="" + title;
                return false;
            });
        });
    </script>
</body>
</html>
");

        }
    }
}
