//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YJC.Toolkit.Razor.Dynamic {
    using System;
    using System.Text;
    using System.Collections.Generic;
    using System.Linq;
    using System.IO;
    using YJC.Toolkit.Razor;
    using YJC.Toolkit.Web;
    using YJC.Toolkit.Sys;
    
    
    public class dcinternalfilemitucorpweixinwebxmlrazorcxcslianxicshtml : YJC.Toolkit.Razor.ToolkitTemplate {
        
#line hidden
        
        public dcinternalfilemitucorpweixinwebxmlrazorcxcslianxicshtml() {
        }
        
        public override void Execute() {
WriteLiteral("<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    <title>联系我们</title>\r\n    <meta");

WriteLiteral(" http-equiv=\"X-UA-Compatible\"");

WriteLiteral(" content=\"IE=edge\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" http-equiv=\"Content-Type\"");

WriteLiteral(" content=\"text/html; charset=utf-8\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable" +
"=0;\"");

WriteLiteral(" />\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteAttribute("href", Tuple.Create(" href=\"", 421), Tuple.Create("\"", 494)
, Tuple.Create(Tuple.Create("", 428), Tuple.Create<System.Object, System.Int32>("toolkitjs/v5/bootstrap/css/bootstrap.min.css".AppVirutalPath()
, 428), false)
);

WriteLiteral(" />\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteAttribute("href", Tuple.Create(" href=\"", 542), Tuple.Create("\"", 621)
, Tuple.Create(Tuple.Create("", 549), Tuple.Create<System.Object, System.Int32>("toolkitjs/v5/bootstrap/css/bootstrap-theme.min.css".AppVirutalPath()
, 549), false)
);

WriteLiteral(" />\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteAttribute("href", Tuple.Create(" href=\"", 669), Tuple.Create("\"", 745)
, Tuple.Create(Tuple.Create("", 676), Tuple.Create<System.Object, System.Int32>("toolkitjs/v5/bootstrap/css/font-awesome.min.css".AppVirutalPath()
, 676), false)
);

WriteLiteral(" />\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteAttribute("href", Tuple.Create(" href=\"", 793), Tuple.Create("\"", 857)
, Tuple.Create(Tuple.Create("", 800), Tuple.Create<System.Object, System.Int32>("toolkitcss/v5/commonM/style.css?v=1".AppVirutalPath()
, 800), false)
);

WriteLiteral(" />\r\n    ");

WriteLiteral("\r\n</head>\r\n<body");

WriteLiteral(" id=\"WebInsertXmlPage\"");

WriteLiteral(" class=\"tk-dataPage\"");

WriteLiteral(" data-webpath=\"/WebSite/\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" id=\"metaData\"");

WriteLiteral(" class=\"hide\"");

WriteLiteral(" data-toolbar=\"false\"");

WriteLiteral(" data-option=\"false\"");

WriteLiteral("></div>\r\n");

WriteLiteral("        ");

   Write(RenderLocalPartial("EditTitle.cshtml", null));

WriteLiteral("\r\n        <address");

WriteLiteral(" class=\"mt15\"");

WriteLiteral(">\r\n            <strong>慈溪市地方税务局城区税务分局</strong><br />\r\n            地址：慈溪市古塘街道开发大道3" +
"18号<br />\r\n            联系电话：0574-63029931<br />\r\n        </address>\r\n        <di" +
"v");

WriteLiteral(" id=\"Map\"");

WriteLiteral(" class=\"mt10 mb10 h300 w100p\"");

WriteLiteral(">\r\n        </div>\r\n    </div>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 1512), Tuple.Create("\"", 1576)
, Tuple.Create(Tuple.Create("", 1518), Tuple.Create<System.Object, System.Int32>("toolkitjs/v5/lib/jquery-1.7.2.min.js".AppVirutalPath()
, 1518), false)
);

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 1623), Tuple.Create("\"", 1693)
, Tuple.Create(Tuple.Create("", 1629), Tuple.Create<System.Object, System.Int32>("toolkitjs/v5/bootstrap/js/bootstrap.min.js".AppVirutalPath()
, 1629), false)
);

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 1740), Tuple.Create("\"", 1799)
, Tuple.Create(Tuple.Create("", 1746), Tuple.Create<System.Object, System.Int32>("toolkitjs/v5/toolkit/toolkit.js".AppVirutalPath()
, 1746), false)
);

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 1846), Tuple.Create("\"", 1916)
, Tuple.Create(Tuple.Create("", 1852), Tuple.Create<System.Object, System.Int32>("toolkitjs/v5/toolkit/coreT/toolkit.page.js".AppVirutalPath()
, 1852), false)
);

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 1963), Tuple.Create("\"", 2037)
, Tuple.Create(Tuple.Create("", 1969), Tuple.Create<System.Object, System.Int32>("toolkitjs/v5/toolkit/coreT/toolkit.data.js?v=7".AppVirutalPath()
, 1969), false)
);

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 2084), Tuple.Create("\"", 2160)
, Tuple.Create(Tuple.Create("", 2090), Tuple.Create<System.Object, System.Int32>("toolkitjs/v5/toolkit/coreT/toolkit.weixin.js?v=5".AppVirutalPath()
, 2090), false)
);

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 2207), Tuple.Create("\"", 2275)
, Tuple.Create(Tuple.Create("", 2213), Tuple.Create<System.Object, System.Int32>("toolkitjs/v5/toolkit/coreT/toolkit.ui.js".AppVirutalPath()
, 2213), false)
);

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(" src=\"http://map.qq.com/api/js?v=2.exp\"");

WriteLiteral(@"></script>
    <script>
        function createQQMap2(id, lng, lat, caption, level) {
            var center = new qq.maps.LatLng(lat, lng);
            var map = new qq.maps.Map(document.getElementById(id), {
                zoom: level,
                scaleControl: true,
                draggable: false,
                center: center
            });
            var marker = new qq.maps.Marker({
                position: center,
                map: map,
                title: caption,
                clickable: false,
            });
        }
        var lat = 30.292506;
        var lng = 121.310381;
        var bMap = createQQMap2(""Map"", lng, lat, ""慈溪市地方税务局城区税务分局"", 15);
    </script>

</body>
</html>
");

        }
    }
}
